### ISSUE TITLE
NPE: GenerationJobExecutionListener unhandled exception within open transaction

### ISSUE THREAD

**Issue by acumarav** [OHDSI/WebAPI#1209]
Under some circumstances unhandled exception might occur at line 81 which breaks BatchJob logic and leave uncommitted transaction....
actual code line:
info.setExecutionDuration((int) (je.getEndTime().getTime() - je.getStartTime().getTime()));

At least must be  handled and logged properly 

Exception encountered in afterStep callback
java.lang.NullPointerException
    at org.ohdsi.webapi.cohortdefinition.GenerationJobExecutionListener.afterJob(GenerationJobExecutionListener.java:81)
    at org.springframework.batch.core.listener.CompositeJobExecutionListener.afterJob(CompositeJobExecutionListener.java:60)
    at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:352)
    at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
2019-06-21 10:16:39.586 INFO taskExecutor-5 org.springframewo

**Comment by anthonysena** [comment]
@acumarav - can you provide steps to reproduce this error? Do you have a sample cohort definition which forces this to occur? Without this information, I suspect the root cause of this issue will be difficult to find.

**Comment by acumarav** [comment]
Hello @anthonysena - this exception was found in the logs during the testing. There are no clear steps to reproduce but it might occur. I want to rework this part of code a bit to make it a bit more readable and add more logging, what do you think?
