### ISSUE TITLE
WebAPI startup fails due to circular dependency in org.bouncycastle:bcprov

### ISSUE THREAD

**Issue by JamesSWiggins** [OHDSI/WebAPI#1302]
I've noticed that I occasionally get the below error when I initially deploy WebAPI in Tomcat 8.  Restarting Tomcat seems to resolve it, but until I restart it WebAPI doesn't respond to any API requests.  Have you seen this before?  Is it, perhaps, addressed in 2.7.3?

20-Aug-2019 12:52:49.455 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChil
d: start:
        org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardC
ontext[/WebAPI]]
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1851)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)
        Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/WebAPI] due toa StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The classhierarchy being processed was [org.bouncycastle.asn1.ASN1Boolean->org.bouncycastle.asn1.DERBoolean->org.bouncycastle.asn1.ASN1Boolean]
                at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2116)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2054)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:2000)
                at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1970)
                at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1923)
                at org.apache.catalina.startup.ContextConfig.processClasses(ContextConfig.java:1230)
                at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1134)
                at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:769)
                at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
                at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5134)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
                ... 10 more
20-Aug-2019 12:52:49.457 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/var/lib/tomcat8/webapps/WebAPI.war]
        java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/WebAPI]]
                at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:758)
                at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
                at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
                at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980)
                at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1851)
                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at java.lang.Thread.run(Thread.java:748)

**Comment by chrisknoll** [comment]
I have not seen this before:
```
Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/WebAPI] due toa StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The classhierarchy being processed was [org.bouncycastle.asn1.ASN1Boolean->org.bouncycastle.asn1.DERBoolean->org.bouncycastle.asn1.ASN1Boolean]
```

This hierarchy looks circular:  ASN1Boolean -> DERBoolean->ASN1Boolean.  I don't know what would be causing that, and I don't know why it wouldn't be re-producible every time.  I'll do a google search on it and see what I can come up with.

**Comment by chrisknoll** [comment]
I found this SO post:
https://stackoverflow.com/questions/29955410/how-do-i-fix-stackoverflowerror-in-org-apache-catalina-startup-contextconfig-pop

Seems there could be 2 fixes here: 
1. Exclude the jar from being scanned by catalina via the tomcat.util.scan.StandardJarScanFilter.jarsToSkip property, and skip `bcprov*.jar`
2. There could be 2 versions of the library found on your classpath (for example `bcprov-jdk15on` and `bcprov-jdk16`.  We could use maven exclusions to exclude one or the other.

I ran `mvn dependency:tree -Dverbose -Dincludes=org.bouncycastle` on my local build (from the 2.7.3-RC1 tag), and this was the output:
```
[INFO] org.ohdsi:WebAPI:war:2.7.3-SNAPSHOT
[INFO] \- org.bouncycastle:bcprov-jdk15on:jar:1.59:compile
```
So, in my env, only one jar was identified.  Maybe on your env you will find multiple JARs (assuming it is a multi-jar problem)

**Comment by pavgra** [comment]
We faced the issue at one point of time and therefore created the PR - https://github.com/OHDSI/WebAPI/pull/1266. But it has gone later so we haven't merged the PR

**Comment by JamesSWiggins** [comment]
Adding this line:
tomcat.util.scan.StandardJarScanFilter.jarsToSkip=bcprov*.jar

To this file:
/etc/tomcat8/catalina.properties

Seems to prevent the error, but that seems like a workaround.

**Comment by chrisknoll** [comment]
I agree, it's a work around.  It may take a bit more effort to clean up the circular dependency properly so we'll look into making those updates in the pom.xml.  

Note: updated description to make this issue more specific.

**Comment by JamesSWiggins** [comment]
In the meantime, I've included that jar skip configuration into the OHDSIonAWS automation.

**Comment by anthonysena** [comment]
Just adding to this issue: Should we adopt the approach in https://github.com/OHDSI/WebAPI/pull/1266/files to address this issue via WebAPI configuration vs Tomcat configuration? Tagging @pavgra @chrisknoll for input.

**Comment by anthonysena** [comment]
Closing this as the `<exclusion>` approach done in #1266 is now in the pom.xml on master.
