### ISSUE TITLE
Special Tomcat configuration required to handle URLs with square brackets

### ISSUE THREAD

**Issue by JamesSWiggins** [OHDSI/WebAPI#1316]
I'm occasionally seeing the below messages in Tomcat catalina.out with WebAPI v2.7.2:

28-Aug-2019 10:24:36.277 INFO [http-nio-8080-exec-10] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:483)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:684)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)

It seems like this could be caused by having query strings with 'raw square brackets' according to this other issue:  (https://github.com/bohnman/squiggly/issues/42#issuecomment-414673274).  Do you all think this is the case?  If so, there is special Tomcat configuration I can apply in the OHDSIonAWS automation that theoretically resolves this.  I haven't tried it though.

**Comment by anthonysena** [comment]
Hi @JamesSWiggins - catching up a bit here and I think that this could be related to an endpoint that is taking an array of values in the query string. Off the top of my head, I'm unsure where in the application uses an array of values via the query string. So, it might be worth digging through some logs where you see this to see what was requested and perhaps that would give us some more to investigate here.

**Comment by anthonysena** [comment]
Closing this out due to age.
