### ISSUE TITLE
NullPointerException in GenerationCacheHelper

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#1351]
After pulling from master, I found several changes to the result schema that I needed to change in order for the cohort generation process to execute:

```
ALTER TABLE cknoll1.cohort_inclusion ADD generation_id int NULL;
ALTER TABLE cknoll1.cohort_inclusion_result ADD generation_id int NULL;
ALTER TABLE cknoll1.cohort_inclusion_stats ADD generation_id int NULL;
ALTER TABLE cknoll1.cohort_summary_stats ADD generation_id int NULL;
ALTER TABLE cknoll1.cohort_censor_stats ADD generation_id int NULL;
```
Note: because this schema has to support 2.7 and 2.8, instead of replacing the column 'cohort_id' with 'generation_id' I just added the new 'generation_id' column to the result.  Also: i made the column null.  I do not know what the value of generation_id should be if there are existing results.

This got me past some 'invalid column name' issues that I was experiencing generating the cohort, but after I got past that, I am having issues related to a NullPointerException.  I'm having trouble narrowing it down to what the actual null value is since the new code is a bit convoluted with the nested lambda expressions and multiple interface abstraction layers.  But, below is the stack trace, and hopefully someone will be able to reproduce this and identify a fix.

I think that we need to have explicit null-value checks in the code and report the problems specific messages so that problems like this are easier to debug.

Stack Trace:

```
org.ohdsi.webapi.exception.AtlasException: java.lang.NullPointerException
        at org.ohdsi.webapi.common.generation.TransactionalTasklet.execute(TransactionalTasklet.java:42)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
        at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:392)
        at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.ohdsi.webapi.util.CancelableJdbcTemplate$1BatchUpdateStatementCallback.doInStatement(CancelableJdbcTemplate.java:69)
        at org.ohdsi.webapi.util.CancelableJdbcTemplate$1BatchUpdateStatementCallback.doInStatement(CancelableJdbcTemplate.java:1)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)
        at org.ohdsi.webapi.util.CancelableJdbcTemplate.batchUpdate(CancelableJdbcTemplate.java:96)
        at org.ohdsi.webapi.generationcache.GenerationCacheHelper.runCancelableCohortGeneration(GenerationCacheHelper.java:74)
        at org.ohdsi.webapi.cohortdefinition.GenerateCohortTasklet.lambda$0(GenerateCohortTasklet.java:88)
        at org.ohdsi.webapi.generationcache.GenerationCacheHelper.computeCacheIfAbsent(GenerationCacheHelper.java:57)
        at org.ohdsi.webapi.cohortdefinition.GenerateCohortTasklet.prepareQueries(GenerateCohortTasklet.java:84)
        at org.ohdsi.webapi.common.generation.CancelableTasklet.doTask(CancelableTasklet.java:33)
        at org.ohdsi.webapi.common.generation.CancelableTasklet.doTask(CancelableTasklet.java:1)
        at org.ohdsi.webapi.common.generation.TransactionalTasklet.lambda$0(TransactionalTasklet.java:37)
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
        at org.ohdsi.webapi.common.generation.TransactionalTasklet.execute(TransactionalTasklet.java:37)
        ... 18 more
```

**Comment by wivern** [comment]
@chrisknoll I could not reproduce exactly the same issue. But anyway I've fixed Sql Server and Oracle migrations that was broken. 
And I guess possible reason of the NPE is the `CancelableJdbcTemplate` trying to rethrow next exception. That also was fixed.

**Comment by chrisknoll** [comment]
Thanks, @wivern. I'll check the branch and report if the exception persists.

**Comment by chrisknoll** [comment]
Ok, after pulling branch from #1352, the fix there let me see the underlying exception, which was:

```
can not inert null value into cohort_definition_id
```

So, that was a problem on my side trying to get a schema to work together with 2.7.4 and 2.8.0.  This is a problem, however, that I should not have to try to find a work around. There should be some level of compatibility between 2.7.4 and 2.8.0, and changing column names violates that.

So, I'd like to re-visit cohort caching mechanism and make it more inter-version friendly.  I'll open up a new issue to track that.  As far as this PR #1352 goes, I think it adds the improvement of exposing the exception, although there's other issues related to triggers which should be addressed.
