### ISSUE TITLE
Characterization execution fails on SQL Server

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/WebAPI#1381]
### Expected 

Characterization execution complete without error

### Experienced

Characterization execution fails with `SQL state [S00078]; error code [539]; Schema changed after the target table was created.` 

### Environment

WebAPI 2.7.4 > Linux (Docker Container, Broadsea)

#### Trace

```
2019-12-06 20:55:08.862 INFO taskExecutor-10 org.springframework.batch.core.job.SimpleStepHandler -  - Executing step: [generateCohortCharacterization.generate]
2019-12-06 20:55:10.332 ERROR taskExecutor-10 org.ohdsi.webapi.cohortcharacterization.GenerateCohortCharacterizationTasklet -  - java.util.concurrent.ExecutionException: org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [SELECT
        CAST(ethnicity_concept_id  AS BIGINT) * 1000 + 5 AS covariate_id,
        COUNT(*) AS sum_value
INTO results.y1lh151d_cov_1
FROM results.temp_cohort_y1lh151d cohort
INNER JOIN dbo.person
        ON cohort.subject_id = person.person_id
WHERE ethnicity_concept_id  IN (
                SELECT concept_id
                FROM dbo.concept
                WHERE LOWER(concept_class_id) = 'ethnicity'
                )
                AND cohort.cohort_definition_id = 444
GROUP BY ethnicity_concept_id
; INSERT INTO results.y1lh151d_cov_ref (
        covariate_id,
        covariate_name,
        analysis_id,
        concept_id
        )
SELECT covariate_id,
        CAST(CONCAT('ethnicity = ', CASE WHEN concept_name IS NULL THEN 'Unknown concept' ELSE concept_name END) AS VARCHAR(512)) AS covariate_name,
        5 AS analysis_id,
        CAST((covariate_id - 5) / 1000 AS INT) AS concept_id
FROM (
        SELECT DISTINCT covariate_id
        FROM results.y1lh151d_cov_1
        ) t1
LEFT JOIN dbo.concept
        ON concept_id = CAST((covariate_id - 5) / 1000 AS INT); INSERT INTO results.y1lh151d_analysis_ref (
        analysis_id,
        analysis_name,
        domain_id,
        start_day,
        end_day,
        is_binary,
        missing_means_zero
        )
SELECT 5 AS analysis_id,
        CAST('DemographicsEthnicity' AS VARCHAR(512)) AS analysis_name,
        CAST('Demographics' AS VARCHAR(20)) AS domain_id,
        CAST(NULL AS INT) AS start_day,
        CAST(NULL AS INT) AS end_day,
        CAST('Y' AS VARCHAR(1)) AS is_binary,
        CAST(NULL AS VARCHAR(1)) AS missing_means_zero; insert into results.cc_results (type, fa_type, covariate_id, covariate_name, analysis_id, analysis_name, concept_id, count_value, avg_value,
                                                 strata_id, strata_name, cohort_definition_id, cc_generation_id)
  select CAST('PREVALENCE' AS VARCHAR(255)) as type,
    CAST('PRESET' AS VARCHAR(255)) as fa_type,
    f.covariate_id,
    fr.covariate_name,
    ar.analysis_id,
    ar.analysis_name,
    fr.concept_id,
    f.sum_value     as count_value,
    f.average_value as stat_value,
    0 as strata_id,
    CAST('' AS VARCHAR(1000)) as strata_name,
    444 as cohort_definition_id,
    4771 as cc_generation_id
  from (select 444 as cohort_definition_id, covariate_id, sum_value, average_value from (SELECT all_covariates.covariate_id,
  all_covariates.sum_value,
  CAST(all_covariates.sum_value / (1.0 * total.total_count) AS FLOAT) AS average_value
FROM (SELECT covariate_id, sum_value FROM results.y1lh151d_cov_1
) all_covariates, (
SELECT COUNT(*) AS total_count
FROM results.temp_cohort_y1lh151d
WHERE cohort_definition_id = 444
) total) W) f
    join (select 444 as cohort_definition_id, covariate_id, covariate_name, analysis_id, concept_id from (SELECT covariate_id, covariate_name, analysis_id, concept_id  FROM results.y1lh151d_cov_ref) W) fr on fr.covariate_id = f.covariate_id and fr.cohort_definition_id = f.cohort_definition_id
    join (select 444 as cohort_definition_id, CAST(analysis_id AS INT) analysis_id, analysis_name, domain_id, start_day, end_day, CAST(is_binary AS CHAR(1)) is_binary,CAST(missing_means_zero AS CHAR(1)) missing_means_zero from (SELECT analysis_id, analysis_name, domain_id, start_day, end_day, is_binary, missing_means_zero FROM results.y1lh151d_analysis_ref) W) ar
      on ar.analysis_id = fr.analysis_id and ar.cohort_definition_id = fr.cohort_definition_id
    left join dbo.concept c on c.concept_id = fr.concept_id; TRUNCATE TABLE results.y1lh151d_cov_1; DROP TABLE results.y1lh151d_cov_1; TRUNCATE TABLE results.y1lh151d_cov_ref; DROP TABLE results.y1lh151d_cov_ref; TRUNCATE TABLE results.y1lh151d_analysis_ref; DROP TABLE results.y1lh151d_analysis_ref]; SQL state [S00078]; error code [539]; Schema changed after the target table was created. Rerun the Select Into query.; nested exception is java.sql.BatchUpdateException: Schema changed after the target table was created. Rerun the Select Into query.
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.springframework.jdbc.UncategorizedSQLException: [...]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:90)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:418)
        at org.ohdsi.webapi.util.CancelableJdbcTemplate.batchUpdate(CancelableJdbcTemplate.java:96)
        at org.ohdsi.webapi.common.generation.CancelableTasklet.lambda$doTask$0(CancelableTasklet.java:35)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: java.sql.BatchUpdateException: Schema changed after the target table was created. Rerun the Select Into query.
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeBatch(SQLServerStatement.java:1816)
        at org.ohdsi.webapi.util.CancelableJdbcTemplate$1BatchUpdateStatementCallback.doInStatement(CancelableJdbcTemplate.java:57)
        at org.ohdsi.webapi.util.CancelableJdbcTemplate$1BatchUpdateStatementCallback.doInStatement(CancelableJdbcTemplate.java:43)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:407)
        ... 6 more
2019-12-06 20:55:10.807 INFO taskExecutor-10 org.springframework.batch.core.launch.support.SimpleJobLauncher -  - Job: [SimpleJob: [name=generateCohortCharacterization]] completed with the following parameters: [{jobName=Generating cohort characterization 39 : CUMC (inpatient and outpatient) - 2019 Q2 (CUMC_inpatient_and_outpatient_2019q2), cohort_characterization_id=39, source_id=2, jobAuthor=taa7016, sessionId=y1lh151d, target_table=temp_cohort_y1lh151d, time=1575665695257}] and the following status: [FAILED]
```

**Comment by t-abdul-basser** [comment]
@chrisknoll @anthonysena @pavgra This exception began to be thrown on all characterization executions after an recent upgrade to 2.7.2+ in one of our deployment instances. The issue appears to be with the `SELECT INTO #TABLE]`. 
Before I experiment with modify the code to use [explicit transactions or source table locks](https://www.sqlservercentral.com/forums/topic/schema-changed-after-the-target-table-was-created-rerun-the-select-into-query#post-1498683) I wanted to ask for your thoughts.

**Comment by anthonysena** [comment]
@t-abdul-basser - can you share the characterization design that is causing the error? Or an example that produces this error? Also, do you happen to know if this characterization generation failed previously?

**Comment by t-abdul-basser** [comment]
Sample characterization design
```
{
  "name": "cc-smoketest-1",
  "cohorts": [
    {
      "id": 1,
      "name": "taa7015:test:hypertension",
      "description": null,
      "createdDate": "2018-01-23 22:09",
      "modifiedDate": "2018-02-26 14:25",
      "expression": {
        "cdmVersionRange": ">=5.0.0",
        "PrimaryCriteria": {
          "CriteriaList": [
            {
              "ConditionOccurrence": {
                "CodesetId": 0,
                "ConditionTypeExclude": false
              }
            }
          ],
          "ObservationWindow": {
            "PriorDays": 0,
            "PostDays": 0
          },
          "PrimaryCriteriaLimit": {
            "Type": "First"
          }
        },
        "ConceptSets": [
          {
            "id": 0,
            "name": "taa7015:test:hypertension",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 320128,
                    "CONCEPT_NAME": "Essential hypertension",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "59621000",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4321603,
                    "CONCEPT_NAME": "Essential hypertension complicating AND/OR reason for care during puerperium",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "9901000",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4180283,
                    "CONCEPT_NAME": "Systolic essential hypertension",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "429457004",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4086587,
                    "CONCEPT_NAME": "Elevated blood pressure",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "24184005",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4023995,
                    "CONCEPT_NAME": "Cardiovascular finding",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "106063007",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4215640,
                    "CONCEPT_NAME": "Benign essential hypertension complicating AND/OR reason for care during childbirth",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "71874008",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4047779,
                    "CONCEPT_NAME": "Disorder by body site",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "123946008",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4042140,
                    "CONCEPT_NAME": "Finding by site",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "118234003",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4274025,
                    "CONCEPT_NAME": "Disease",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "64572001",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 134057,
                    "CONCEPT_NAME": "Disorder of cardiovascular system",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "49601007",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4180628,
                    "CONCEPT_NAME": "Disorder of body system",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "362965005",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4159755,
                    "CONCEPT_NAME": "Labile essential hypertension",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "371125006",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4083723,
                    "CONCEPT_NAME": "Essential hypertension complicating AND/OR reason for care during childbirth",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "18416000",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4302591,
                    "CONCEPT_NAME": "Essential hypertension complicating AND/OR reason for care during pregnancy",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "78808002",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 316866,
                    "CONCEPT_NAME": "Hypertensive disorder",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "38341003",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 312648,
                    "CONCEPT_NAME": "Benign essential hypertension",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "1201005",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 317898,
                    "CONCEPT_NAME": "Malignant essential hypertension",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "78975002",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4217486,
                    "CONCEPT_NAME": "Essential hypertension in obstetric context",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "72022006",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4034031,
                    "CONCEPT_NAME": "Benign essential hypertension complicating AND/OR reason for care during pregnancy",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "23717007",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4148205,
                    "CONCEPT_NAME": "Benign essential hypertension complicating AND/OR reason for care during puerperium",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "35303009",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4058987,
                    "CONCEPT_NAME": "High-renin essential hypertension",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "19769006",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4263067,
                    "CONCEPT_NAME": "Low-renin essential hypertension",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "46481004",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 45757787,
                    "CONCEPT_NAME": "Postpartum pre-existing essential hypertension",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "40511000119107",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 4269358,
                    "CONCEPT_NAME": "Benign essential hypertension in obstetric context",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "63287004",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                },
                {
                  "concept": {
                    "CONCEPT_ID": 441840,
                    "CONCEPT_NAME": "Clinical finding",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "404684003",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": false,
                  "includeMapped": false
                }
              ]
            }
          }
        ],
        "QualifiedLimit": {
          "Type": "First"
        },
        "ExpressionLimit": {
          "Type": "First"
        },
        "InclusionRules": [],
        "CensoringCriteria": [],
        "CollapseSettings": {
          "CollapseType": "ERA",
          "EraPad": 0
        }
      }
    }
  ],
  "featureAnalyses": [
    {
      "id": 72,
      "type": "PRESET",
      "name": "Demographics Race",
      "domain": "DEMOGRAPHICS",
      "statType": "PREVALENCE",
      "descr": "Race of the subject.",
      "design": "DemographicsRace",
      "description": "Race of the subject."
    },
    {
      "id": 74,
      "type": "PRESET",
      "name": "Demographics Gender",
      "domain": "DEMOGRAPHICS",
      "statType": "PREVALENCE",
      "descr": "Gender of the subject.",
      "design": "DemographicsGender",
      "description": "Gender of the subject."
    },
    {
      "id": 77,
      "type": "PRESET",
      "name": "Demographics Age",
      "domain": "DEMOGRAPHICS",
      "statType": "DISTRIBUTION",
      "descr": "Age of the subject on the index date (in years).",
      "design": "DemographicsAge",
      "description": "Age of the subject on the index date (in years)."
    }
  ],
  "parameters": [],
  "stratas": [],
  "strataOnly": false,
  "strataConceptSets": [],
  "createdAt": "2019-11-19 20:53:38",
  "updatedAt": null,
  "skeletonType": "CohortCharacterizationStudy",
  "skeletonVersion": "v0.0.1",
  "packageName": null,
  "organizationName": "OHDSI",
  "stratifiedBy": null
}
```

It did not fail previously.

**Comment by chrisknoll** [comment]
Reading [here](https://dba.stackexchange.com/questions/230491/disk-space-full-during-insert-what-happens), it seems what could be happening here is the table was created but the insert failed due to space issue?  That may lead to the 'schema has changed, re-run insert' error.  In the case where it works, is the insert small, and where it fails, could it be large?

**Comment by anthonysena** [comment]
@t-abdul-basser - just following up on this to see if this issue is still present or if there was anything in your environment that was changed to correct this issue? From re-reading this thread, I am not sure if this is related to WebAPI or if it is environment specific. If you have any details that you can share that would be appreciated. If not, could we close this one?

**Comment by anthonysena** [comment]
Closing due to inactivity.
