### ISSUE TITLE
Cohort Generation Cache:  ERROR: duplicate key value violates unique constraint "uq_gc_hash"

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#1471]
The following error is reported when failing to generate a cohort.  I'm unable to share the specific cohort details that results in this error; there seems to be a case where a duplicate generation hash is calculated and stored.  

Logs:

```
2020-02-29 04:50:31.892 ERROR taskExecutor-2 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - ERROR: duplicate key value violates unique constraint "uq_gc_hash"
  Detail: Key (type, design_hash, source_id)=(COHORT, 1431287467, 235) already exists.
2020-02-29 04:50:31.892 ERROR taskExecutor-2 org.ohdsi.webapi.cohortdefinition.GenerateCohortTasklet -  - org.hibernate.exception.ConstraintViolationException: could not execute statement
...
...
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at org.ohdsi.webapi.generationcache.$Proxy238.saveAndFlush(Unknown Source)
	at org.ohdsi.webapi.generationcache.GenerationCacheServiceImpl.cacheResults(GenerationCacheServiceImpl.java:79)
	at org.ohdsi.webapi.generationcache.GenerationCacheHelper.computeCacheIfAbsent(GenerationCacheHelper.java:60)
	at org.ohdsi.webapi.cohortdefinition.GenerateCohortTasklet.prepareQueries(GenerateCohortTasklet.java:82)
	at org.ohdsi.webapi.common.generation.CancelableTasklet.doTask(CancelableTasklet.java:33)

...
...
```

It appears that when the cache is persisted in GenerationCacheServiceImpl.cacheResults():

```
        GenerationCache generationCache = new GenerationCache();
        generationCache.setType(type);
        generationCache.setDesignHash(designHash);
        generationCache.setSource(source);
        generationCache.setResultChecksum(checksum);
        generationCache.setCreatedDate(new Date());

        generationCache = generationCacheRepository.saveAndFlush(generationCache);

        log.info(CACHE_CREATED, type, designHash);
```

The question is, when would `cacheResults()` be invoked when there already exists a design hash for the cohort in the database?  Is it a race condition, or for some reason one branch calcluates the design hash differently than another?

**Comment by anthonysena** [comment]
@olga-ganina can someone on your team investigate? Thanks!

**Comment by ParkChanghHyun** [comment]
#1874 
Cache mechanism destroyed Data consistency .
