### ISSUE TITLE
Changing design of Characterization Feature Failed

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1642]
based on https://github.com/OHDSI/Atlas/issues/2343
WebApi 2.8

**Expected behavior**
After changing a design of characterization feature, from Criteria to Custom, saving of the feature is working

**Actual behavior**
After changing a design of characterization feature, from Criteria to Custom, saving of the feature is NOT working, getting an error message

![image](https://user-images.githubusercontent.com/56290675/94813210-63742800-0400-11eb-91b0-0d72c2c4b6ef.png)

**Logs:**
Request URL: WebAPI/feature-analysis/155
Request Method: PUT
Status Code: 500 

{"payload":{"cause":null,"stackTrace":[],"message":"An exception ocurred: java.lang.ClassCastException","localizedMessage":"An exception ocurred: java.lang.ClassCastException","suppressed":[]},"headers":{"id":"d9266864-a6f5-7fb9-b355-9180fdf715d7","timestamp":1601557713673}}

```
2020-10-01 13:04:36.034 ERROR http-nio-8080-exec-9 org.ohdsi.webapi.util.GenericExceptionMapper -  - java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at org.ohdsi.webapi.feanalysis.domain.FeAnalysisWithCriteriaEntity.setDesign(FeAnalysisWithCriteriaEntity.java:11)
	at org.ohdsi.webapi.feanalysis.FeAnalysisServiceImpl.updateAnalysis(FeAnalysisServiceImpl.java:169)
	at org.ohdsi.webapi.feanalysis.FeAnalysisServiceImpl$$FastClassBySpringCGLIB$$1cad7af8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
	at org.ohdsi.webapi.feanalysis.FeAnalysisServiceImpl$$EnhancerBySpringCGLIB$$33db4284.updateAnalysis(<generated>)
	at org.ohdsi.webapi.feanalysis.FeAnalysisController.updateAnalysis(FeAnalysisController.java:99)
	at org.ohdsi.webapi.feanalysis.FeAnalysisController$$FastClassBySpringCGLIB$$a67f86b9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
	at org.ohdsi.webapi.feanalysis.FeAnalysisController$$EnhancerBySpringCGLIB$$fbb24667.updateAnalysis(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at 
```
**Steps to reproduce the behavior**
Create a New Feature -> Pick 'Criteria' as design -> Save Feature -> Change design to 'Custom' -> Try to Save and get an Error

**Comment by wivern** [comment]
@KSadomtsev it seems changing of feature analysis type should be prohibited after one was saved.
This operation is just the same as delete and create a new feature analysis. But I believe this should be doing transparently to users since re-creation of feature analysis means characterizations includes this FA were also changed and might require recalculation.
