### ISSUE TITLE
Getting Vocabulary Does Not Exists

### ISSUE THREAD

**Issue by umesh-clinakos** [OHDSI/WebAPI#1675]
Getting the "cmsdesynpuf23m.vocabulary" does not exist error. Any help to resolve this would be appreciated. Following is the stack trace if the error.

ERROR http-nio-8080-exec-8 org.ohdsi.webapi.util.Generic                                                                                                             ExceptionMapper -  - org.springframework.jdbc.BadSqlGrammarException: PreparedSt                                                                                                             atementCallback; bad SQL grammar [select VOCABULARY_VERSION
from CMSDESynPUF23m.vocabulary
where VOCABULARY_ID = 'None']; nested exception is java.sql.SQLException: [Amazo                                                                                                             n](500310) Invalid operation: relation "cmsdesynpuf23m.vocabulary" does not exis                                                                                                             t;
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.d                                                                                                             oTranslate(SQLErrorCodeSQLExceptionTranslator.java:230)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslat                                                                                                             or.translate(AbstractFallbackSQLExceptionTranslator.java:73)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:                                                                                                             654)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:68                                                                                                             8)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:72                                                                                                             0)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:73                                                                                                             0)
        at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplat                                                                                                             e.java:798)
        at org.ohdsi.webapi.service.VocabularyService.getInfo(VocabularyService.                                                                                                             java:851)
        at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                             sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHa                                                                                                             ndlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethod                                                                                                             Dispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethod                                                                                                             Dispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatch                                                                                                             erProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:2                                                                                                             05)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethod                                                                                                             Dispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(Resour                                                                                                             ceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(Resourc                                                                                                             eMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(Resourc                                                                                                             eMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:32                                                                                                             6)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(Request                                                                                                             Scope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:                                                                                                             305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHand                                                                                                             ler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.ja                                                                                                             va:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:4                                                                                                             27)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContaine                                                                                                             r.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContaine                                                                                                             r.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContaine                                                                                                             r.java:228)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52                                                                                                             )
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.ohdsi.webapi.shiro.filters.ResponseNoCacheFilter.doFilter(Respons                                                                                                             eNoCacheFilter.java:26)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:118)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(Abstrac                                                                                                             tShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiro                                                                                                             Filter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallab                                                                                                             le.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable                                                                                                             .java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(Delegating                                                                                                             Subject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(Abs                                                                                                             tractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.ohdsi.webapi.shiro.filters.CacheFilter.doFilter(CacheFilter.java:                                                                                                             30)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.ohdsi.webapi.shiro.filters.ExceptionHandlerFilter.doFilter(Except                                                                                                             ionHandlerFilter.java:28)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(                                                                                                             RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInter                                                                                                             nal(HttpPutFormContentFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInterna                                                                                                             l(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterIntern                                                                                                             al(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPa                                                                                                             geFilter.java:130)
        at org.springframework.boot.web.support.ErrorPageFilter.access$000(Error                                                                                                             PageFilter.java:66)
        at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterIntern                                                                                                             al(ErrorPageFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPa                                                                                                             geFilter.java:123)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV                                                                                                             alve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV                                                                                                             alve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica                                                                                                             torBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j                                                                                                             ava:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j                                                                                                             ava:81)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:74                                                                                                             7)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAcce                                                                                                             ssLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal                                                                                                             ve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav                                                                                                             a:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java                                                                                                             :615)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig                                                                                                             ht.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract                                                                                                             Protocol.java:818)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo                                                                                                             int.java:1626)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas                                                                                                             e.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                             java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                             .java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh                                                                                                             read.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: [Amazon](500310) Invalid operation: relation "                                                                                                             cmsdesynpuf23m.vocabulary" does not exist;
        at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorExce                                                                                                             ption(Unknown Source)
        at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unk                                                                                                             nown Source)
        at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown S                                                                                                             ource)
        at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessage                                                                                                             OfClass(Unknown Source)
        at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unkno                                                                                                             wn Source)
        at com.amazon.redshift.client.PGMessagingContext.getParameterDescription                                                                                                             (Unknown Source)
        at com.amazon.redshift.client.PGClient.prepareStatement(Unknown Source)
        at com.amazon.redshift.dataengine.PGQueryExecutor.<init>(Unknown Source)
        at com.amazon.redshift.dataengine.PGDataEngine.prepare(Unknown Source)
        at com.amazon.jdbc.common.SPreparedStatement.<init>(Unknown Source)
        at com.amazon.jdbc.jdbc4.S4PreparedStatement.<init>(Unknown Source)
        at com.amazon.redshift.core.jdbc4.PGJDBC4PreparedStatement.<init>(Unknow                                                                                                             n Source)
        at com.amazon.redshift.core.jdbc4.PGJDBC4ObjectFactory.createPreparedSta                                                                                                             tement(Unknown Source)
        at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
        at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
        at org.springframework.jdbc.core.JdbcTemplate$SimplePreparedStatementCre                                                                                                             ator.createPreparedStatement(JdbcTemplate.java:1525)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:                                                                                                             632)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:68                                                                                                             8)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:72                                                                                                             0)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:73                                                                                                             0)
        at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplat                                                                                                             e.java:798)
        at org.ohdsi.webapi.service.VocabularyService.getInfo(VocabularyService.                                                                                                             java:851)
        at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces                                                                                                             sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHa                                                                                                             ndlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethod                                                                                                             Dispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethod                                                                                                             Dispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatch                                                                                                             erProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:2                                                                                                             05)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethod                                                                                                             Dispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(Resour                                                                                                             ceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(Resourc                                                                                                             eMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(Resourc                                                                                                             eMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:32                                                                                                             6)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(Request                                                                                                             Scope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:                                                                                                             305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHand                                                                                                             ler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.ja                                                                                                             va:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:4                                                                                                             27)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContaine                                                                                                             r.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContaine                                                                                                             r.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContaine                                                                                                             r.java:228)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52                                                                                                             )
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:61)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.ohdsi.webapi.shiro.filters.ResponseNoCacheFilter.doFilter(Respons                                                                                                             eNoCacheFilter.java:26)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:118)
        at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilte                                                                                                             rChain.java:66)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(Abstrac                                                                                                             tShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiro                                                                                                             Filter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallab                                                                                                             le.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable                                                                                                             .java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(Delegating                                                                                                             Subject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(Abs                                                                                                             tractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.j                                                                                                             ava:108)
        at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilt                                                                                                             er.java:137)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerReq                                                                                                             uestFilter.java:125)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.ohdsi.webapi.shiro.filters.CacheFilter.doFilter(CacheFilter.java:                                                                                                             30)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.ohdsi.webapi.shiro.filters.ExceptionHandlerFilter.doFilter(Except                                                                                                             ionHandlerFilter.java:28)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(                                                                                                             RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInter                                                                                                             nal(HttpPutFormContentFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInterna                                                                                                             l(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterIntern                                                                                                             al(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPa                                                                                                             geFilter.java:130)
        at org.springframework.boot.web.support.ErrorPageFilter.access$000(Error                                                                                                             PageFilter.java:66)
        at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterIntern                                                                                                             al(ErrorPageFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerR                                                                                                             equestFilter.java:107)
        at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPa                                                                                                             geFilter.java:123)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl                                                                                                             icationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF                                                                                                             ilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV                                                                                                             alve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV                                                                                                             alve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica                                                                                                             torBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j                                                                                                             ava:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j                                                                                                             ava:81)
        at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:74                                                                                                             7)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAcce                                                                                                             ssLogValve.java:690)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal                                                                                                             ve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav                                                                                                             a:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java                                                                                                             :615)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLig                                                                                                             ht.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(Abstract                                                                                                             Protocol.java:818)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpo                                                                                                             int.java:1626)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBas                                                                                                             e.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.                                                                                                             java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor                                                                                                             .java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskTh                                                                                                             read.java:61)
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invali                                                                                                             d operation: relation "cmsdesynpuf23m.vocabulary" does not exist;
        ... 133 more

**Comment by chrisknoll** [comment]
What kind of assistance do you need?  It is telling you the vocabulary table does not exist.  Do you know how to create it?

**Comment by umesh-clinakos** [comment]
Yes. I need to know how and where to create it.

**Comment by anthonysena** [comment]
The vocabulary tables should be created when establishing your CDM. Please refer to https://ohdsi.github.io/CommonDataModel/index.html for more details.
