### ISSUE TITLE
[FA] IllegalArgumentException: Invalid CriteriaColumn for Condition Occurrence:QUANTITY

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1705]
webApi 2.8

1)Create CC analysis
2)Create FA with distribution type
3)Add procedure occurrence criteria
4)Select Procedure -> Quantity
5)Save FA
6)Add FA to characterization 
7)Run analysis

Actual:
`org.ohdsi.webapi.exception.AtlasException: java.lang.IllegalArgumentException: Invalid CriteriaColumn for Condition Occurrence:QUANTITY
	at org.ohdsi.webapi.common.generation.TransactionalTasklet.execute(TransactionalTasklet.java:42)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:392)
	at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid CriteriaColumn for Condition Occurrence:QUANTITY
	at org.ohdsi.circe.cohortdefinition.builders.ProcedureOccurrenceSqlBuilder.getTableColumnForCriteriaColumn(ProcedureOccurrenceSqlBuilder.java:44)
	at org.ohdsi.circe.cohortdefinition.builders.CriteriaSqlBuilder.lambda$getAdditionalColumns$1(CriteriaSqlBuilder.java:51)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline`

**Comment by chrisknoll** [comment]
Just some additional information: that exception comes from the back-end when you request a column to be returned from the criteria query, but the quested column isn't a column that is available.  In this case, it is saying that you requested a Quantity column of ConditionOccurrnence, but your steps says you added a procedure occurrence.  Therefore I believe the error is that the 'adding procedure' is incorrectly adding a ConditionOccurrence criteria to the object model.

**Comment by anton-abushkevich** [comment]
@chrisknoll 

> 
> 
> Just some additional information: that exception comes from the back-end when you request a column to be returned from the criteria query, but the requested column isn't a column that is available. In this case, it is saying that you requested a Quantity column of ConditionOccurrnence, but your steps says you added a procedure occurrence. Therefore I believe the error is that the 'adding procedure' is incorrectly adding a ConditionOccurrence criteria to the object model.

There is a typo in "Invalid CriteriaColumn for Condition Occurrence:QUANTITY", it shoud be "Invalid CriteriaColumn for Procedure Occurrence:QUANTITY". And indeed, there is missing case for quantity column. Please see the pull request, i assigned it to you.

**Comment by chrisknoll** [comment]
Thanks, working on this now. i just needed to add test cases for the change, but It's being processed now. I'll approve as soon as the CI tests pass.
