### ISSUE TITLE
Characterization import from 2.7 failed(FA with "statType": "DISTRIBUTION")

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1706]
webAPi 2.8

Steps:

1)Try to Import design from 2.7: 
[cc_design.txt](https://github.com/OHDSI/WebAPI/files/5614622/cc_design.txt)

Expected:
Successful import

Actual:
`2020-11-30 08:25:47.393 ERROR http-nio-8080-exec-5 org.ohdsi.webapi.util.GenericExceptionMapper -  - java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy252.importCc(Unknown Source)
	at org.ohdsi.webapi.cohortcharacterization.CcController.doImport(CcController.java:183)
	at org.ohdsi.webapi.cohortcharacterization.CcController$$FastClassBySpringCGLIB$$ce604349.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)`

**Comment by KSadomtsev** [comment]
Verified
