### ISSUE TITLE
Failed to get feature analysis data(ConversionFailedException)

### ISSUE THREAD

**Issue by DKashenko** [OHDSI/WebAPI#1758]
WebApi 2.8.1 (in 2.8 it works fine)

Steps:

1. Login by admin
2. Characterizations -> Feature Analysis
3. Try to open any analysis

Actual:
<img width="735" alt="Loader CC" src="https://user-images.githubusercontent.com/77493858/105696857-e1f75700-5f14-11eb-8c25-346479a7ff87.png">

WebAPI/feature-analysis
Request Method: GET
Status Code: 500

{"payload":{"cause":null,"stackTrace":[],"message":"An exception occurred: org.springframework.core.convert.ConversionFailedException","localizedMessage":"An exception occurred: org.springframework.core.convert.ConversionFailedException","suppressed":[]},"headers":{"id":"7c8e257e-0e5b-8cd3-4559-df9b7eff8518","timestamp":1611571544778}}

```
2021-01-25 10:35:07.328 ERROR http-nio-8080-exec-4 org.ohdsi.webapi.util.GenericExceptionMapper -  - org.springframework.core.convert.ConversionFailedException: Failed to convert from type [org.ohdsi.webapi.feanalysis.domain.FeAnalysisWithPrevalenceCriteriaEntity] to type [org.ohdsi.webapi.feanalysis.dto.FeAnalysisDTO] for value 'org.ohdsi.webapi.feanalysis.domain.FeAnalysisWithPrevalenceCriteriaEntity@d0'; nested exception is org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.ohdsi.webapi.feanalysis.domain.FeAnalysisWithCriteriaEntity.design, could not initialize proxy - no Session
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:44)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:203)
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:187)
	at org.ohdsi.webapi.feanalysis.FeAnalysisController.convertFeAnalysisToDto(FeAnalysisController.java:227)
	at org.ohdsi.webapi.feanalysis.FeAnalysisController.getFeAnalysis(FeAnalysisController.java:125)
	at org.ohdsi.webapi.feanalysis.FeAnalysisController$$FastClassBySpringCGLIB$$a67f86b9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:667)
	at org.ohdsi.webapi.feanalysis.FeAnalysisController$$EnhancerBySpringCGLIB$$80cb8f85.getFeAnalysis(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
```

**Comment by KSadomtsev** [comment]
@ssuvorov-fls reproduced again on  <hibernate.version>5.4.18
