### ISSUE TITLE
SQL State S0001, Error Code (156), Incorrect syntax near the keyword 'IF' raise on v2.8.0 initializattion

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/WebAPI#1769]
### Expected behavior

WebAPI 2.8.x succeeds on initialization.

### Actual behavior

WebAPI 2.8.x fails on initialization.

### Steps to reproduce behavior

1. Install v2.8.0 and start.

### Trace
```
 .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v1.5.20.RELEASE)

<...>
2021-02-03 01:18:46.714 INFO main org.flywaydb.core.internal.util.VersionPrinter -  - Flyway 4.2.0 by Boxfuse
2021-02-03 01:18:51.331 INFO main org.flywaydb.core.internal.dbsupport.DbSupportFactory -  - Database: jdbc:sqlserver://[redacted]:1433;useBulkCopyForBatchInsert=false;cancelQueryTimeout=-1;sslProtocol=TLS;jaasConfigurationName=SQLJDBCDriver;statementPoolingCacheSize=0;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=webapi;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 11.0)
2021-02-03 01:18:53.896 INFO main org.flywaydb.core.internal.command.DbMigrate -  - Current version of schema [dbo]: 2.8.0.20200109132902
2021-02-03 01:18:53.897 WARN main org.flywaydb.core.internal.command.DbMigrate -  - outOfOrder mode is active. Migration of schema [dbo] may not be reproducible.
2021-02-03 01:18:53.930 INFO main org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema [dbo] to version 2.8.0.20200116134252 - remove obsolete field pathway event cohort deleted id
2021-02-03 01:18:54.018 ERROR main org.flywaydb.core.internal.command.DbMigrate -  - Migration of schema [dbo] to version 2.8.0.20200116134252 - remove obsolete field pathway event cohort deleted id failed! Changes successfully rolled back.
2021-02-03 01:18:54.121 INFO main org.flywaydb.core.internal.dbsupport.sqlserver.SQLServerDbSupport -  - SQLServer does not support setting the schema for the current session. Default schema NOT changed to dbo
2021-02-03 01:18:54.127 WARN main org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext -  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shiroFilter' defined in class path resource [org/ohdsi/webapi/ShiroConfiguration.class]: Unsatisfied dependency expressed through method 'shiroFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/ohdsi/webapi/FlywayConfig.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
Migration V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql failed
-------------------------------------------------------------------------------------------------
SQL State  : S0001
Error Code : 156
Message    : Incorrect syntax near the keyword 'IF'.
Location   : db/migration/sqlserver/V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql (/usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/db/migration/sqlserver/V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql)
Line       : 2
Statement  : declare @command nvarchar(1000)
select @command = 'ALTER TABLE dbo.pathway_event_cohort DROP CONSTRAINT IF EXISTS ' + d.name
from sys.tables t
  join sys.default_constraints d on d.parent_object_id = t.object_id
  join sys.columns c on c.object_id = t.object_id and c.column_id = d.parent_column_id
where
  t.name = 'pathway_event_cohort'
  and t.schema_id = schema_id('dbo')
  and c.name = 'is_deleted';
execute (@command)

ALTER TABLE dbo.pathway_event_cohort DROP COLUMN IF EXISTS is_deleted;

2021-02-03 01:18:54.189 INFO main org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer -  - 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2021-02-03 01:18:54.217 ERROR main org.springframework.boot.SpringApplication -  - Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shiroFilter' defined in class path resource [org/ohdsi/webapi/ShiroConfiguration.class]: Unsatisfied dependency expressed through method 'shiroFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/ohdsi/webapi/FlywayConfig.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
Migration V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql failed
-------------------------------------------------------------------------------------------------
SQL State  : S0001
Error Code : 156
Message    : Incorrect syntax near the keyword 'IF'.
Location   : db/migration/sqlserver/V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql (/usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/db/migration/sqlserver/V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql)
Line       : 2
Statement  : declare @command nvarchar(1000)
select @command = 'ALTER TABLE dbo.pathway_event_cohort DROP CONSTRAINT IF EXISTS ' + d.name
from sys.tables t
  join sys.default_constraints d on d.parent_object_id = t.object_id
  join sys.columns c on c.object_id = t.object_id and c.column_id = d.parent_column_id
where
  t.name = 'pathway_event_cohort'
  and t.schema_id = schema_id('dbo')
  and c.name = 'is_deleted';
execute (@command)

ALTER TABLE dbo.pathway_event_cohort DROP COLUMN IF EXISTS is_deleted;

        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1072)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:237)
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:703)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:527)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:156)
        at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:136)
        at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:434)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/ohdsi/webapi/FlywayConfig.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
Migration V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql failed
-------------------------------------------------------------------------------------------------
SQL State  : S0001
Error Code : 156
Message    : Incorrect syntax near the keyword 'IF'.
Location   : db/migration/sqlserver/V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql (/usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/db/migration/sqlserver/V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql)
Line       : 2
Statement  : declare @command nvarchar(1000)
select @command = 'ALTER TABLE dbo.pathway_event_cohort DROP CONSTRAINT IF EXISTS ' + d.name
from sys.tables t
  join sys.default_constraints d on d.parent_object_id = t.object_id
  join sys.columns c on c.object_id = t.object_id and c.column_id = d.parent_column_id
where
  t.name = 'pathway_event_cohort'
  and t.schema_id = schema_id('dbo')
  and c.name = 'is_deleted';
execute (@command)

ALTER TABLE dbo.pathway_event_cohort DROP COLUMN IF EXISTS is_deleted;

        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1630)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:297)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1139)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1067)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:835)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 60 more
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
Migration V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql failed
-------------------------------------------------------------------------------------------------
SQL State  : S0001
Error Code : 156
Message    : Incorrect syntax near the keyword 'IF'.
Location   : db/migration/sqlserver/V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql (/usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/db/migration/sqlserver/V2.8.0.20200116134252__remove_obsolete_field_pathway_event_cohort_deleted_id.sql)
Line       : 2
Statement  : declare @command nvarchar(1000)
select @command = 'ALTER TABLE dbo.pathway_event_cohort DROP CONSTRAINT IF EXISTS ' + d.name
from sys.tables t
  join sys.default_constraints d on d.parent_object_id = t.object_id
  join sys.columns c on c.object_id = t.object_id and c.column_id = d.parent_column_id
where
  t.name = 'pathway_event_cohort'
  and t.schema_id = schema_id('dbo')
  and c.name = 'is_deleted';
execute (@command)

ALTER TABLE dbo.pathway_event_cohort DROP COLUMN IF EXISTS is_deleted;

        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:345)
        at org.flywaydb.core.internal.command.DbMigrate.access$900(DbMigrate.java:53)
        at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:276)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
        at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:53)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:210)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:146)
        at org.flywaydb.core.internal.dbsupport.DbSupport$1.call(DbSupport.java:223)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
        at org.flywaydb.core.internal.dbsupport.DbSupport.lock(DbSupport.java:219)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:146)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1010)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:971)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1464)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:971)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1759)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1696)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1626)
        ... 73 more
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near the keyword 'IF'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.doExecuteStatement(SQLServerStatement.java:859)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement$StmtExecCmd.doExecute(SQLServerStatement.java:759)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.execute(SQLServerStatement.java:739)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
        at com.sun.proxy.$Proxy94.execute(Unknown Source)
        at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:267)
        at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:142)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:76)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:343)
        ... 96 more
```

**Comment by t-abdul-basser** [comment]
@chrisknoll @anthonysena @pavgra Is SQL Server 2016+ a requirement?

**Comment by chrisknoll** [comment]
No, but some people are using SQL2016 syntax. For this specific issue, I've posted PR #1764, which we'll try to push out in 2.8.1 (soon to be released).  If you want, you can try to build off the branch in that PR, but we'll try to get this into master ASAP.

**Comment by t-abdul-basser** [comment]
OK. I will test. 
It was going to suggest [this](https://github.com/t-abdul-basser/WebAPI/commit/aea2538c3f078c235028adb773a48cd376f2b891).

**Comment by chrisknoll** [comment]
Ok, if that's what's required, that's a good approach.  These migration scripts, however, shouldn't need to check for the existence of a column:  if the migrations are applied successfully, then the column will be there.  The reason for the 'IF EXISTS" was that an existing migration script was altered to not include a column, and then subsequent scripts had to check if the column existed (to handle both cases when the col was defined vs. when the col wasn't defined (after the migration was changed).  The 'proper' way for all of this is migration scripts that make it into master should not be modified, only adjusted via a subsequent migration script.  But the rule was broken in this case, so we'll have to make it work.

Let me know if the branch fails, and if your approach works, we can PR that into master.

**Comment by t-abdul-basser** [comment]
I used your fix.
