### ISSUE TITLE
Tomcat reserved memory

### ISSUE THREAD

**Issue by mgabetta** [OHDSI/WebAPI#1811]
Hi!
I'm experiencing an issue with WebAPI.
During Tomcat startup I have this error:

```
2021-03-08 19:32:04.547 ERROR taskExecutor-1 org.springframework.batch.core.step.AbstractStep -  - Encountered an error executing step warming SYN0 cache results in job warming SYN0 cache
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.collections.impl.map.mutable.ConcurrentHashMapUnsafe.resize(ConcurrentHashMapUnsafe.java:314)
	at org.eclipse.collections.impl.map.mutable.ConcurrentHashMapUnsafe.resize(ConcurrentHashMapUnsafe.java:283)
	at org.eclipse.collections.impl.map.mutable.ConcurrentHashMapUnsafe.incrementSizeAndPossiblyResize(ConcurrentHashMapUnsafe.java:237)
	at org.eclipse.collections.impl.map.mutable.ConcurrentHashMapUnsafe.slowPut(ConcurrentHashMapUnsafe.java:960)
	at org.eclipse.collections.impl.map.mutable.ConcurrentHashMapUnsafe.put(ConcurrentHashMapUnsafe.java:922)
	at org.ohdsi.webapi.cdmresults.cache.CDMResultsCache.cacheValue(CDMResultsCache.java:91)
	at org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet.lambda$null$0(CDMResultsCacheTasklet.java:96)
	at org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet$$Lambda$300/98908396.processRow(Unknown Source)
	at org.springframework.jdbc.core.JdbcTemplate$RowCallbackHandlerResultSetExtractor.extractData(JdbcTemplate.java:1575)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:701)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:638)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:688)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:720)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:745)
	at org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet.lambda$warmCdmCache$1(CDMResultsCacheTasklet.java:94)
	at org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet$$Lambda$299/1039100745.doInTransaction(Unknown Source)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet.warmCdmCache(CDMResultsCacheTasklet.java:93)
	at org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet.warm(CDMResultsCacheTasklet.java:69)
	at org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet.execute(CDMResultsCacheTasklet.java:61)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:392)
2021-03-08 19:32:04.580 INFO taskExecutor-1 org.springframework.batch.core.launch.support.SimpleJobLauncher -  - Job: [SimpleJob: [name=warming SYN0 cache]] completed with the following parameters: [{jobName=warming SYN0 cache, time=1615228303074, jobAuthor=anonymous}] and the following status: [FAILED]
```

What is the advised memory size to be reserved for Tomcat?

**Comment by chrisknoll** [comment]
One of the more memory-hungry elements of the WebAPI service is the caching for the vocabulary counts (and other report-level services).  I'd suggest at least 2GB allocation, depending on your data sources.

**Comment by mgabetta** [comment]
@chrisknoll , thanks for the fast answer.
I think I'm giving 4GB to Tomcat but, given your answer, I'm not sure I've set it up in the correct way. Here's what Tomcat logs at startup:

```
08-Mar-2021 18:56:16.826 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/9.0.43
08-Mar-2021 18:56:16.828 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jan 28 2021 20:25:45 UTC
08-Mar-2021 18:56:16.828 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 9.0.43.0
08-Mar-2021 18:56:16.828 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
08-Mar-2021 18:56:16.828 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.4.17-2036.103.3.1.el8uek.x86_64
08-Mar-2021 18:56:16.829 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
08-Mar-2021 18:56:16.829 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/java/jdk1.8.0_281-amd64/jre
08-Mar-2021 18:56:16.829 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_281-b09
08-Mar-2021 18:56:16.829 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
08-Mar-2021 18:56:16.829 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /opt/tomcat/apache-tomcat-9.0.43
08-Mar-2021 18:56:16.829 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /opt/tomcat/apache-tomcat-9.0.43
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/opt/tomcat/latest/conf/logging.properties
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dfile.encoding=UTF-8
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms256m
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2048m
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:PermSize=256m
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxPermSize=1024m
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512M
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024M
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/opt/tomcat/latest
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/opt/tomcat/latest
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/opt/tomcat/latest/temp
```

**Comment by mgabetta** [comment]
I forgot: for the moment I'm using CDM_synthea as the data source, so I don't think the task should be much demanding...

**Comment by chrisknoll** [comment]
I'm not sure could be a combination of JDK you're using OS, and settings.  One thing that strikes me as odd is:

```
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms256m
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2048m
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:PermSize=256m
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxPermSize=1024m
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
08-Mar-2021 18:56:16.830 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms512M
08-Mar-2021 18:56:16.831 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024M
```

I see the -Xms being specified twice, and the one with the larger value puts a lowercase 'm' as the unit.

**Comment by mgabetta** [comment]
you're right. I was setting xmx twice...and the lowest was the second...thanks for helping!

```
2021-03-08 21:20:04.406 INFO taskExecutor-1 org.springframework.batch.core.job.SimpleStepHandler -  - Executing step: [warming SYN0 cache data density]
2021-03-08 21:20:04.635 INFO taskExecutor-1 org.springframework.batch.core.job.SimpleStepHandler -  - Executing step: [warming SYN0 cache results]
2021-03-08 21:20:13.828 INFO taskExecutor-1 org.springframework.batch.core.launch.support.SimpleJobLauncher -  - Job: [SimpleJob: [name=warming SYN0 cache]] completed with the following parameters: [{jobName=warming SYN0 cache, time=1615234798856, jobAuthor=anonymous}] and the following status: [COMPLETED]
```
