### ISSUE TITLE
version discrepancy issue

### ISSUE THREAD

**Issue by wyriwyg** [OHDSI/WebAPI#1875]
### Expected behavior
If a specific version of WebAPI, Atlas is used, flyaway migration should be recognizing it correctly
### Actual behavior
using WebAPI/Atlas 2.7.4, but flyway takes it as 2.8.0
### Steps to reproduce behavior
here are the details:
We are following the instruction [here](https://github.com/OHDSI/Broadsea) to install OHDSI stack in docker container, we are seeing all the tables created, and we have a backend CDM database, we setup the source and source_domain, all seems to be good, but it Atlas is still not up, due some strange error (see below).

Since our backend CDM is 2.7.4, so we are using 2.7.4 for WebAPI and Atlas. And we really have no idea about the error message here. Also strange is that the log says `INFO main org.flywaydb.core.internal.command.DbMigrate -  - Current version of schema "webapi": 2.8.0.20190604111801`, which is strange, since we are using 2.7.4. 

Could some one kindly take a look? Thank you in advance!

    root@4c18e4365469:/var/log/supervisor# tail -1000 *stdout*

    2021-04-30 19:05:08.097 INFO main org.springframework.beans.factory.support.DefaultListableBeanFactory -  - Overriding bean definition for bean 'requestContextFilter' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration; factoryMethodName=requestContextFilter; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/jersey/JerseyAutoConfiguration.class]] with [Root bean: class [org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=requestContextFilter; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
    2021-04-30 19:05:08.379 INFO main org.springframework.integration.config.IntegrationRegistrar -  - No bean named 'integrationHeaderChannelRegistry' has been explicitly defined. Therefore, a default DefaultHeaderChannelRegistry will be created.
    2021-04-30 19:05:08.799 INFO main org.springframework.integration.config.DefaultConfiguringBeanFactoryPostProcessor -  - No bean named 'errorChannel' has been explicitly defined. Therefore, a default PublishSubscribeChannel will be created.
    2021-04-30 19:05:08.819 INFO main org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor -  - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
    2021-04-30 19:05:08.897 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'converterConfiguration' of type [org.ohdsi.webapi.ConverterConfiguration$$EnhancerBySpringCGLIB$$f2a64de2] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:08.929 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'conversionService' of type [org.springframework.core.convert.support.DefaultConversionService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:09.200 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$8c0b2696] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:09.417 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'shiroConfiguration' of type [org.ohdsi.webapi.ShiroConfiguration$$EnhancerBySpringCGLIB$$d0798c91] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:09.432 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'flywayConfig' of type [org.ohdsi.webapi.FlywayConfig$$EnhancerBySpringCGLIB$$8eaed8ea] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:10.244 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'secondaryDataSource' of type [org.apache.tomcat.jdbc.pool.DataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:10.263 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$$EnhancerBySpringCGLIB$$6dfec9f6] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:10.355 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:10.368 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'dataSourceInitializer' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:10.485 INFO main org.flywaydb.core.internal.util.VersionPrinter -  - Flyway 4.2.0 by Boxfuse
    2021-04-30 19:05:10.834 INFO main org.flywaydb.core.internal.dbsupport.DbSupportFactory -  - Database: jdbc:postgresql://host.docker.internal:5432/DockerOHDSI (PostgreSQL 13.2)
    2021-04-30 19:05:11.048 INFO main org.flywaydb.core.internal.command.DbMigrate -  - Current version of schema "webapi": 2.8.0.20190604111801
    2021-04-30 19:05:11.048 WARN main org.flywaydb.core.internal.command.DbMigrate -  - outOfOrder mode is active. Migration of schema "webapi" may not be reproducible.
    2021-04-30 19:05:11.049 INFO main org.flywaydb.core.internal.command.DbMigrate -  - Schema "webapi" is up to date. No migration necessary.
    2021-04-30 19:05:11.052 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'flyway' of type [org.flywaydb.core.Flyway] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:11.062 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'disabledSecurity' of type [org.ohdsi.webapi.shiro.management.DisabledSecurity] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:11.073 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'noLockoutPolicy' of type [org.ohdsi.webapi.shiro.lockout.NoLockoutPolicy] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:11.137 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'securityManager' of type [org.ohdsi.webapi.shiro.lockout.LockoutWebSecurityManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:11.208 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'integrationGlobalProperties' of type [org.springframework.beans.factory.config.PropertiesFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:11.209 INFO main org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker -  - Bean 'integrationGlobalProperties' of type [java.util.Properties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
    2021-04-30 19:05:11.252 INFO main org.springframework.web.context.ContextLoader -  - Root WebApplicationContext: initialization completed in 4853 ms
    2021-04-30 19:05:12.027 INFO main org.springframework.jdbc.datasource.DriverManagerDataSource -  - Loaded JDBC driver: org.postgresql.Driver
    2021-04-30 19:05:12.029 INFO main org.ohdsi.webapi.DataAccessConfig -  - driver loaded: org.postgresql.Driver
    2021-04-30 19:05:12.050 INFO main org.ohdsi.webapi.DataAccessConfig -  - driver loaded: com.microsoft.sqlserver.jdbc.SQLServerDriver
    2021-04-30 19:05:12.051 INFO main org.ohdsi.webapi.DataAccessConfig -  - error loading oracle.jdbc.driver.OracleDriver driver. oracle.jdbc.driver.OracleDriver
    2021-04-30 19:05:12.080 INFO main org.ohdsi.webapi.DataAccessConfig -  - driver loaded: com.amazon.redshift.jdbc.Driver
    2021-04-30 19:05:12.080 INFO main org.ohdsi.webapi.DataAccessConfig -  - error loading com.cloudera.impala.jdbc.Driver driver. com.cloudera.impala.jdbc.Driver
    2021-04-30 19:05:12.081 INFO main org.ohdsi.webapi.DataAccessConfig -  - error loading net.starschema.clouddb.jdbc.BQDriver driver. net.starschema.clouddb.jdbc.BQDriver
    2021-04-30 19:05:12.082 INFO main org.ohdsi.webapi.DataAccessConfig -  - error loading org.netezza.Driver driver. org.netezza.Driver
    2021-04-30 19:05:12.082 INFO main org.ohdsi.webapi.DataAccessConfig -  - error loading com.simba.googlebigquery.jdbc42.Driver driver. com.simba.googlebigquery.jdbc42.Driver
    2021-04-30 19:05:12.204 INFO main org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean -  - Building JPA container EntityManagerFactory for persistence unit 'default'
    2021-04-30 19:05:12.230 INFO main org.hibernate.jpa.internal.util.LogHelper -  - HHH000204: Processing PersistenceUnitInfo [name: default]
    2021-04-30 19:05:12.379 INFO main org.hibernate.Version -  - HHH000412: Hibernate Core {5.4.2.Final}
    2021-04-30 19:05:12.670 INFO main org.hibernate.annotations.common.Version -  - HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
    2021-04-30 19:05:13.127 INFO main org.hibernate.dialect.Dialect -  - HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
    2021-04-30 19:05:13.897 WARN main org.hibernate.mapping.RootClass -  - HHH000038: Composite-id class does not override equals(): org.ohdsi.webapi.conceptset.ConceptSetGenerationInfoKey
    2021-04-30 19:05:13.898 WARN main org.hibernate.mapping.RootClass -  - HHH000039: Composite-id class does not override hashCode(): org.ohdsi.webapi.conceptset.ConceptSetGenerationInfoKey
    2021-04-30 19:05:15.324 INFO main org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator -  - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
    2021-04-30 19:05:15.327 INFO main org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean -  - Initialized JPA EntityManagerFactory for persistence unit 'default'
    2021-04-30 19:05:16.871 INFO main org.springframework.boot.web.servlet.ServletRegistrationBean -  - Mapping servlet: 'org.ohdsi.webapi.JerseyConfig' to [/*]
    2021-04-30 19:05:16.872 INFO main org.springframework.boot.web.servlet.ServletRegistrationBean -  - Mapping servlet: 'dispatcherServlet' to [/]
    2021-04-30 19:05:16.873 INFO main org.springframework.boot.web.servlet.FilterRegistrationBean -  - Mapping filter: 'errorPageFilter' to: [/*]
    2021-04-30 19:05:16.873 INFO main org.springframework.boot.web.servlet.FilterRegistrationBean -  - Mapping filter: 'characterEncodingFilter' to: [/*]
    2021-04-30 19:05:16.873 INFO main org.springframework.boot.web.servlet.FilterRegistrationBean -  - Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
    2021-04-30 19:05:16.873 INFO main org.springframework.boot.web.servlet.FilterRegistrationBean -  - Mapping filter: 'httpPutFormContentFilter' to: [/*]
    2021-04-30 19:05:16.873 INFO main org.springframework.boot.web.servlet.FilterRegistrationBean -  - Mapping filter: 'requestContextFilter' to: [/*]
    2021-04-30 19:05:16.873 INFO main org.springframework.boot.web.servlet.FilterRegistrationBean -  - Mapping filter: 'exceptionHandlerFilter' to: [/*]
    2021-04-30 19:05:16.873 INFO main org.springframework.boot.web.servlet.FilterRegistrationBean -  - Mapping filter: 'cacheFilter' to: [/*]
    2021-04-30 19:05:16.873 INFO main org.springframework.boot.web.servlet.FilterRegistrationBean -  - Mapping filter: 'corsFilter' to: [/*]
    2021-04-30 19:05:16.873 INFO main org.springframework.boot.web.servlet.FilterRegistrationBean -  - Mapping filter: 'shiroFilter' to: [/*]
    2021-04-30 19:05:17.115 INFO main org.springframework.batch.core.repository.support.JobRepositoryFactoryBean -  - No database type set, using meta data indicating: POSTGRES
    2021-04-30 19:05:17.442 INFO main org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor -  - Initializing ExecutorService
    2021-04-30 19:05:17.462 INFO main org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor -  - Initializing ExecutorService 'taskExecutor'
    2021-04-30 19:05:17.620 INFO main org.ehcache.xml.XmlConfiguration -  - Loading Ehcache XML configuration from /usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml.
    2021-04-30 19:05:18.420 INFO main org.ehcache.core.EhcacheManager -  - Cache 'datasources.dashboard' created in EhcacheManager.
    2021-04-30 19:05:18.423 INFO main org.ehcache.core.EhcacheManager -  - Cache 'datasources.domain' created in EhcacheManager.
    2021-04-30 19:05:18.426 INFO main org.ehcache.core.EhcacheManager -  - Cache 'datasources.dataDensity' created in EhcacheManager.
    2021-04-30 19:05:18.429 INFO main org.ehcache.core.EhcacheManager -  - Cache 'datasources.person' created in EhcacheManager.
    2021-04-30 19:05:18.431 INFO main org.ehcache.core.EhcacheManager -  - Cache 'datasources.drilldown' created in EhcacheManager.
    2021-04-30 19:05:18.459 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.dashboard
    2021-04-30 19:05:18.461 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.domain
    2021-04-30 19:05:18.462 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.dataDensity
    2021-04-30 19:05:18.462 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.person
    2021-04-30 19:05:18.462 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.drilldown
    2021-04-30 19:05:19.716 INFO main org.ohdsi.webapi.executionengine.service.ScriptExecutionServiceImpl -  - Invalidating execution engine based analyses
    2021-04-30 19:05:21.241 INFO taskExecutor-1 org.springframework.batch.core.launch.support.SimpleJobLauncher -  - Job: [SimpleJob: [name=warmCache]] launched with the following parameters: [{jobName=warming omop_noPHI_CDM cache, time=1619809521132, jobAuthor=system}]
    2021-04-30 19:05:21.269 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.dashboard
    2021-04-30 19:05:21.270 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.domain
    2021-04-30 19:05:21.270 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.dataDensity
    2021-04-30 19:05:21.270 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.person
    2021-04-30 19:05:21.270 INFO main org.ehcache.jsr107.Eh107CacheManager -  - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=file./usr/local/tomcat/webapps/WebAPI/WEB-INF/classes/config/ehcache.xml,Cache=datasources.drilldown
    2021-04-30 19:05:21.344 INFO taskExecutor-1 org.springframework.batch.core.job.SimpleStepHandler -  - Executing step: [warmCacheStep]
    2021-04-30 19:05:21.598 INFO main org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler -  - Initializing ExecutorService
    2021-04-30 19:05:21.617 INFO main org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler -  - Initializing ExecutorService 'taskScheduler'
    2021-04-30 19:05:22.057 WARN main org.springframework.aop.framework.CglibAopProxy -  - Unable to proxy interface-implementing method [public final void com.odysseusinc.scheduler.service.BaseJobServiceImpl.setApplicationContext(org.springframework.context.ApplicationContext) throws org.springframework.beans.BeansException] because it is marked as final: Consider using interface-based JDK proxies instead!
    2021-04-30 19:05:22.057 INFO main org.springframework.aop.framework.CglibAopProxy -  - Final method [public final void com.odysseusinc.scheduler.service.BaseJobServiceImpl.setApplicationContext(org.springframework.context.ApplicationContext) throws org.springframework.beans.BeansException] cannot get proxied via CGLIB: Calls to this method will NOT be routed to the target instance and might lead to NPEs against uninitialized fields in the proxy instance.
    2021-04-30 19:05:22.057 INFO main org.springframework.aop.framework.CglibAopProxy -  - Final method [protected final com.cronutils.model.time.ExecutionTime com.odysseusinc.scheduler.service.BaseJobServiceImpl.getExecutionTime(com.odysseusinc.scheduler.model.ArachneJob)] cannot get proxied via CGLIB: Calls to this method will NOT be routed to the target instance and might lead to NPEs against uninitialized fields in the proxy instance.
    2021-04-30 19:05:22.407 INFO main org.flywaydb.core.internal.command.DbMigrate -  - Current version of schema "webapi": 2.8.0.20190604111801
    2021-04-30 19:05:22.407 WARN main org.flywaydb.core.internal.command.DbMigrate -  - outOfOrder mode is active. Migration of schema "webapi" may not be reproducible.
    2021-04-30 19:05:22.408 INFO main org.flywaydb.core.internal.command.DbMigrate -  - Schema "webapi" is up to date. No migration necessary.
    2021-04-30 19:05:23.235 INFO main org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter -  - Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1e8e3df8: startup date [Fri Apr 30 19:05:06 UTC 2021]; root of context hierarchy
    2021-04-30 19:05:23.415 INFO main org.springframework.web.servlet.handler.SimpleUrlHandlerMapping -  - Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
    2021-04-30 19:05:23.415 INFO main org.springframework.web.servlet.handler.SimpleUrlHandlerMapping -  - Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
    2021-04-30 19:05:23.503 INFO main org.springframework.web.servlet.handler.SimpleUrlHandlerMapping -  - Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
    2021-04-30 19:05:23.775 INFO main org.springframework.ldap.core.support.AbstractContextSource -  - Property 'userDn' not set - anonymous context will be used for read-write operations
    2021-04-30 19:05:24.933 INFO main org.springframework.jmx.export.annotation.AnnotationMBeanExporter -  - Registering beans for JMX exposure on startup
    2021-04-30 19:05:24.950 INFO main org.springframework.jmx.export.annotation.AnnotationMBeanExporter -  - Bean with name 'integrationMbeanExporter' has been autodetected for JMX exposure
    2021-04-30 19:05:24.953 INFO main org.springframework.jmx.export.annotation.AnnotationMBeanExporter -  - Located managed bean 'integrationMbeanExporter': registering with JMX server as MBean [org.springframework.integration.monitor:name=integrationMbeanExporter,type=IntegrationMBeanExporter]
    2021-04-30 19:05:25.009 INFO main org.springframework.integration.monitor.IntegrationMBeanExporter -  - Registering beans for JMX exposure on startup
    2021-04-30 19:05:25.009 INFO main org.springframework.integration.monitor.IntegrationMBeanExporter -  - Registering MessageChannel nullChannel
    2021-04-30 19:05:25.014 INFO main org.springframework.integration.monitor.IntegrationMBeanExporter -  - Located managed bean 'org.springframework.integration:type=MessageChannel,name=nullChannel': registering with JMX server as MBean [org.springframework.integration:type=MessageChannel,name=nullChannel]
    2021-04-30 19:05:25.026 INFO main org.springframework.integration.monitor.IntegrationMBeanExporter -  - Registering MessageChannel errorChannel
    2021-04-30 19:05:25.028 INFO main org.springframework.integration.monitor.IntegrationMBeanExporter -  - Located managed bean 'org.springframework.integration:type=MessageChannel,name=errorChannel': registering with JMX server as MBean [org.springframework.integration:type=MessageChannel,name=errorChannel]
    2021-04-30 19:05:25.093 INFO main org.springframework.integration.monitor.IntegrationMBeanExporter -  - Registering MessageHandler errorLogger
    2021-04-30 19:05:25.094 INFO main org.springframework.integration.monitor.IntegrationMBeanExporter -  - Located managed bean 'org.springframework.integration:type=MessageHandler,name=errorLogger,bean=internal': registering with JMX server as MBean [org.springframework.integration:type=MessageHandler,name=errorLogger,bean=internal]
    2021-04-30 19:05:25.123 INFO main org.springframework.context.support.DefaultLifecycleProcessor -  - Starting beans in phase 0
    2021-04-30 19:05:25.123 INFO main org.springframework.integration.endpoint.EventDrivenConsumer -  - Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
    2021-04-30 19:05:25.123 INFO main org.springframework.integration.channel.PublishSubscribeChannel -  - Channel 'application:default:8089.errorChannel' has 1 subscriber(s).
    2021-04-30 19:05:25.124 INFO main org.springframework.integration.endpoint.EventDrivenConsumer -  - started _org.springframework.integration.errorLogger
    2021-04-30 19:05:25.124 INFO main org.springframework.context.support.DefaultLifecycleProcessor -  - Starting beans in phase 2147483647
    2021-04-30 19:05:25.157 INFO main org.ohdsi.webapi.WebApi -  - Started WebApi in 19.466 seconds (JVM running for 26.766)
    2021-04-30 19:05:25.191 INFO taskScheduler-2 org.ohdsi.webapi.executionengine.service.ScriptExecutionServiceImpl -  - Invalidating execution engine based analyses
    2021-04-30 19:08:02.207 INFO taskExecutor-1 org.springframework.beans.factory.xml.XmlBeanDefinitionReader -  - Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
    2021-04-30 19:08:02.257 WARN taskExecutor-1 org.springframework.jdbc.support.SQLErrorCodesFactory -  - Error while extracting database name - falling back to empty error codes
    org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is org.postgresql.util.PSQLException: This connection has been closed.
    	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:342)
    	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:366)
    	at org.springframework.jdbc.support.SQLErrorCodesFactory.getErrorCodes(SQLErrorCodesFactory.java:212)
    	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDataSource(SQLErrorCodeSQLExceptionTranslator.java:134)
    	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:97)
    	at org.springframework.jdbc.support.JdbcAccessor.getExceptionTranslator(JdbcAccessor.java:105)
    	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:654)
    	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:688)
    	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:720)
    	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:770)
    	at org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet.warmCache(CDMResultsCacheTasklet.java:66)
    	at org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet.execute(CDMResultsCacheTasklet.java:78)
    	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
    	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
    	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
    	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
    	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
    	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
    	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
    	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
    	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
    	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
    	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
    	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:392)
    	at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
    	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
    	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:829)
    Caused by: org.postgresql.util.PSQLException: This connection has been closed.
    	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:885)
    	at org.postgresql.jdbc.PgConnection.getMetaData(PgConnection.java:1317)
    	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:331)
    	... 29 more
    2021-04-30 19:08:02.261 ERROR taskExecutor-1 org.ohdsi.webapi.cdmresults.CDMResultsCacheTasklet -  - Failed to warm cache for omop_noPHI_CDM. Exception: PreparedStatementCallback; SQL [WITH concepts AS (
        SELECT
          CAST(ancestor_concept_id AS VARCHAR)   ancestor_id,
          CAST(descendant_concept_id AS VARCHAR) descendant_id
        FROM omop_cdm.concept_ancestor ca
        UNION
        SELECT
          CAST(concept_id AS VARCHAR) ancestor_id,
          CAST(concept_id AS VARCHAR) descendant_id
        FROM omop_cdm.concept c
    ), counts AS (
    SELECT stratum_1 concept_id, MAX (count_value) agg_count_value
    FROM results.achilles_results
    WHERE analysis_id IN (2, 4, 5, 201, 225, 301, 325, 401, 425, 501, 505, 525, 601, 625, 701, 725, 801, 825, 
    826, 827, 901, 1001, 1201, 1425, 1801, 1825, 1826, 1827, 2101, 2125, 2301)
    		
    GROUP BY stratum_1
    UNION
    SELECT stratum_2 AS concept_id, SUM (count_value) AS agg_count_value
    FROM results.achilles_results
    WHERE analysis_id IN (405, 605, 705, 805, 807, 1805, 1807, 2105)
    		
    GROUP BY stratum_2
    )
    SELECT
      concepts.ancestor_id               concept_id,
      COALESCE(max(c1.agg_count_value),0) record_count,
      COALESCE(sum(c2.agg_count_value),0) descendant_record_count

    FROM concepts
      LEFT JOIN counts c1 ON concepts.ancestor_id = c1.concept_id
      LEFT JOIN counts c2 ON concepts.descendant_id = c2.concept_id
    GROUP BY concepts.ancestor_id
    ]; An I/O error occurred while sending to the backend.; nested exception is org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
    2021-04-30 19:08:02.330 INFO taskExecutor-1 org.springframework.batch.core.launch.support.SimpleJobLauncher -  - Job: [SimpleJob: [name=warmCache]] completed with the following parameters: [{jobName=warming omop_noPHI_CDM cache, time=1619809521132, jobAuthor=system}] and the following status: [COMPLETED]
    root@4c18e4365469:/var/log/supervisor#

**Comment by chrisknoll** [comment]
According to this tag in our repo, there are 2.8 migration scripts applied to that version:
https://github.com/OHDSI/WebAPI/tree/v2.7.4/src/main/resources/db/migration/sqlserver

However,   This isn't an error, per-se, but rather there were fixes made in version 2.8 that were hot-fixed into 2.7.4.  The reason we keep the migration scripts the same name is that we don't want those migrations to be applied twice.
