### ISSUE TITLE
Error while creating cohort

### ISSUE THREAD

**Issue by pm-ibm** [OHDSI/WebAPI#1956]
### Expected behavior
Able to create cohort

### Actual behavior
Get following error:
```
2021-10-29 22:21:24.229 ERROR http-nio-8080-exec-4 org.ohdsi.webapi.util.GenericExceptionMapper -  - java.lang.NoClassDefFoundError: org/graalvm/polyglot/PolyglotException
	at org.ohdsi.analysis.versioning.CdmVersionUtils.determineCdmCompatibility(CdmVersionUtils.java:27)
	at org.ohdsi.analysis.versioning.VersionedSerializer.serialize(VersionedSerializer.java:21)
	at org.ohdsi.analysis.versioning.VersionedSerializer.serialize(VersionedSerializer.java:9)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3697)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3073)
	at org.ohdsi.analysis.Utils.serialize(Utils.java:172)
	at org.ohdsi.analysis.Utils.serialize(Utils.java:165)
	at org.ohdsi.webapi.service.CohortDefinitionService.createCohortDefinition(CohortDefinitionService.java:406)
	at org.ohdsi.webapi.service.CohortDefinitionService$$FastClassBySpringCGLIB$$3ea7ee83.invoke(<generated>)
```

### Steps to reproduce behavior
Install ohdsi stack using helm charts https://github.com/chgl/charts , Issue discussed in https://github.com/chgl/charts/issues/148

If you can suggest what can be possible issue, we can work on it.

**Comment by anthonysena** [comment]
@pm-ibm - this issue is old and I'm going to close it out. If you are still facing the issue reported here (with the latest Atlas/WebAPI code), could you provide the cohort definition JSON you are using to create the cohort? Thanks!
