### ISSUE TITLE
WebAPI v2.11.0 : Job [warming cache] sql syntax error 

### ISSUE THREAD

**Issue by CGDM-LRocher** [OHDSI/WebAPI#2033]
I have upgraded WebApi/Atlas an existing environement from v2.10.1 to v2.11.0.
I use postgreSQL database.

And now, [warming cache] jobs fails with a Sql Syntax error: 
  ERROR:  syntax error at or near ")" at character 252

I found the sql query that is causing the problem:

select achillesca0_.id as id1_0_, achillesca0_.cache as cache2_0_, achillesca0_.cache_name as cache_na3_0_, achillesca0_.source_id as source_i4_0_ from ohdsi.achilles_cache achillesca0_ where achillesca0_.source_id=$1 and (achillesca0_.cache_name in ())

Problem come from empty list for cache_name  condition.

**Comment by anthonysena** [comment]
@CGDM-LRocher - could you share the stack trace and/or the WebAPI log?

**Comment by anthonysena** [comment]
Tagging @ssuvorov-fls here - how is the `cache_name` set on the newly introduced `achilles_cache` table? I tried to scan the code but was unsure how that is set, presumably during the cache warming process?

**Comment by CGDM-LRocher** [comment]
@anthonysena  I have reproduce issue on my rancher desktop  environnement with log set in debug mode:

[WebApi.log](https://gist.github.com/CGDM-LRocher/319b1d4a7795fd22a6690018c76229a7)

Note: I have force a Refresh cache for start a new job and capture a clean log

Interesting part look to be :

``` txt
at org.ohdsi.webapi.achilles.service.AchillesCacheService.findBySourceAndNames(AchillesCacheService.java:43) ~[classes/:?]
at org.ohdsi.webapi.achilles.service.AchillesCacheService.getEntities(AchillesCacheService.java:85) ~[classes/:?]
at org.ohdsi.webapi.achilles.service.AchillesCacheService.createCacheEntities(AchillesCacheService.java:79) ~[classes/:?]
at org.ohdsi.webapi.achilles.service.AchillesCacheService.saveDrilldownCacheMap(AchillesCacheService.java:74) ~[classes/:?]
at org.ohdsi.webapi.achilles.service.AchillesCacheService$$FastClassBySpringCGLIB$$1a646729.invoke(<generated>) ~[classes/:?]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.25.RELEASE.jar:4.3.25.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.3.25.RELEASE.jar:4.3.25.RELE
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:283) ~[spring-tx-4.3.25.RELEASE.jar:4.3.25
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.25.RELEASE.jar:4.3.25.RELEASE]
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671) ~[spring-aop-4.3.25.RELEASE.jar:4.3.25.RELEASE]
at org.ohdsi.webapi.achilles.service.AchillesCacheService$$EnhancerBySpringCGLIB$$95ef3efd.saveDrilldownCacheMap(<generated>) ~[classes/:?]
at org.ohdsi.webapi.cdmresults.AchillesCacheTasklet.cacheDrilldown(AchillesCacheTasklet.java:146) ~[classes/:?]
at java.util.HashMap$KeySet.forEach(HashMap.java:929) ~[?:?]
at org.ohdsi.webapi.cdmresults.AchillesCacheTasklet.execute(AchillesCacheTasklet.java:221) ~[classes/:?]
```

**Comment by anton-abushkevich** [comment]
Cause of the error is empty conceptNodes in org.ohdsi.webapi.achilles.service.AchillesCacheService.saveDrilldownCacheMap(AchillesCacheService.java:74). I added check, please see pull request #2035.

The reason why conceptNodes map is empty - is probably empty achilles tables in the result schema of the dataset. Please check your source result schema. But anyway, Achilles results are not mandatory, so the check above should be enough to prevent the caching error.
