### ISSUE TITLE
Certificate to the Java certificate store at 

### ISSUE THREAD

**Issue by davidhcar** [OHDSI/WebAPI#2327]
### Expected behavior
Never experienced this error before with the docker build. What I need is an instructions to generate java based certificate, I will then copy over to  '/etc/ssl/certs/java/cacerts' in the dockerfile. 

Thank you in advance!!

### Actual behavior
Setting up ca-certificates-java (20190405) ... 
#6 59.29 head: cannot open '/etc/ssl/certs/java/cacerts' for reading: No such file or directory 
#6 59.53 Exception in thread "main" java.lang.InternalError: Error loading java.security file 
#6 59.53 at java.base/java.security.Security.initialize(Security.java:94) 
#6 59.53 at java.base/java.security.Security$1.run(Security.java:79) 
#6 59.53 at java.base/java.security.Security$1.run(Security.java:77) 
#6 59.53 at java.base/java.security.AccessController.doPrivileged(Native Method) 
#6 59.53 at java.base/java.security.Security.<clinit>(Security.java:77) 
#6 59.53 at java.base/sun.security.jca.ProviderList.<init>(ProviderList.java:176) 
#6 59.53 at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:94) 
#6 59.53 at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:92) 
#6 59.53 at java.base/java.security.AccessController.doPrivileged(Native Method) 
#6 59.53 at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:91) 
#6 59.53 at java.base/sun.security.jca.Providers.<clinit>(Providers.java:54) 
#6 59.53 at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156) 
#6 59.53 at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193) 
#6 59.53 at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50) 
#6 59.53 at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65) 
#6 59.53 at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51) 
#6 59.54 dpkg: error processing package ca-certificates-java (--configure): 
#6 59.54 installed ca-certificates-java package post-installation script subprocess returned error exit status 1 
#6 59.54 Setting up default-jre-headless (2:1.11-71) ... 
#6 59.58 dpkg: dependency problems prevent configuration of openjdk-11-jre-headless:amd64: 
#6 59.58 openjdk-11-jre-headless:amd64 depends on ca-certificates-java (>= 20190405~); however: 
#6 59.58 Package ca-certificates-java is not configured yet. 

### Steps to reproduce behavior
Build WebAPI 2.13 release with Docker image

**Comment by davidhcar** [comment]
@anthonysena @chrisknoll Any idea? It looks like the maven ohdsi repo certificate store is unable to to trust to bring the certificate to local java certificate store at this path,  '/etc/ssl/certs/java/cacerts'

Appreciate your responses. Thank you!

**Comment by chrisknoll** [comment]
Would need @alondhe to chime in.

**Comment by anthonysena** [comment]
From discussion on the Atlas WG, we had noted that there is a recent change to Broadsea that might be helpful: https://github.com/OHDSI/Broadsea/commit/1aad75b649c8bf25ebe9fd750b4589caab4966b2

**Comment by alondhe** [comment]
Sorry for the delay, December was crazy. In Broadsea develop branch, we have made changes to how to use cacerts files:

https://github.com/OHDSI/Broadsea/tree/develop?tab=readme-ov-file#bring-your-own-cacerts-java-keystore-for-ldap-and-snowflake-connections

We don't have coverage of how to generate your cacerts file, but you can find that in many articles online. Generate it (or copy it) on a system in your network that has the proper trusts and then point to it using env variable WEBAPI_CACERTS_FILE.
