### ISSUE TITLE
Cannot open ports on Tomcat

### ISSUE THREAD

**Issue by nzurawski** [OHDSI/WebAPI#2365]
### Expected behavior
Port 8443 to open and respond
### Actual behavior
Port 8443 is unresponsive and running catalina configtest against the tomcat bin directory claims the address is already in use
`23-Apr-2024 15:25:44.712 SEVERE [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector["https-jsse-nio-8443"]]
        org.apache.catalina.LifecycleException: Protocol handler initialization failed
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:1076)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:127)
                at org.apache.catalina.core.StandardService.initInternal(StandardService.java:564)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:127)
                at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:861)
                at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:127)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:596)
                at org.apache.catalina.startup.Catalina.load(Catalina.java:619)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.lang.reflect.Method.invoke(Unknown Source)
                at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:302)
                at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:483)
        Caused by: java.net.BindException: Address already in use: bind
                at sun.nio.ch.Net.bind0(Native Method)
                at sun.nio.ch.Net.bind(Unknown Source)
                at sun.nio.ch.Net.bind(Unknown Source)
                at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
                at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
                at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:218)
                at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:194)
                at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1328)
                at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1341)
                at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:241)
                at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:695)
                at org.apache.coyote.http11.AbstractHttp11Protocol.init(AbstractHttp11Protocol.java:76)
                at org.apache.catalina.connector.Connector.initInternal(Connector.java:1074)
                ... 13 more`
### Steps to reproduce behavior
I have copied Tomcat's server.xml file with keystore password redacted
[server.txt](https://github.com/OHDSI/WebAPI/files/15082052/server.txt)

**Comment by nzurawski** [comment]
Closing this because I have verified separately that despite the results of the catalina configtest, the port is definitely open.
