### ISSUE TITLE
Cohort analysis (runHeraclesAnalyses.sql) in rc_2.3 branch throws errors

### ISSUE THREAD

**Issue by chen-regen** [OHDSI/WebAPI#293]
I am trying to test this against our Oracle. Running a "full report" cause following stack trace:
```
SQL state [null]; error code [17081]; error occurred during batching: ORA-01861: literal does not match format string
; nested exception is java.sql.BatchUpdateException: error occurred during batching: ORA-01861: literal does not match format string

	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:419)
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:600)
	at org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet$1.doInTransaction(CohortAnalysisTasklet.java:64)
	at org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet$1.doInTransaction(CohortAnalysisTasklet.java:1)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet.execute(CohortAnalysisTasklet.java:47)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:272)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:374)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:200)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:392)
	at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:306)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: error occurred during batching: ORA-01861: literal does not match format string

	at oracle.jdbc.driver.OracleStatement.executeBatch(OracleStatement.java:4586)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:230)
	at org.springframework.jdbc.core.JdbcTemplate$1BatchUpdateStatementCallback.doInStatement(JdbcTemplate.java:561)
	at org.springframework.jdbc.core.JdbcTemplate$1BatchUpdateStatementCallback.doInStatement(JdbcTemplate.java:548)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
	... 23 more
```
Looked into the translated SQL for Oracle, it's following statement causing problems:
```
SELECT
DISTINCT 
  EXTRACT(YEAR FROM observation_period_start_date) AS obs_year,
  CAST(TO_CHAR(EXTRACT(YEAR FROM observation_period_start_date) ) || '01' || '01' AS DATE) AS obs_year_start,	
  CAST(TO_CHAR(EXTRACT(YEAR FROM observation_period_start_date) ) || '12' || '31' AS DATE) AS obs_year_end

FROM
OMOPV5_DE.PERSON p1
inner join (SELECT subject_id, cohort_definition_id as cohort_definition_id FROM OHDSI.COHORT   WHERE cohort_definition_id in (2404) ) c1
	on p1.person_id = c1.subject_id
inner join
  OMOPV5_DE.observation_period op1
  on p1.person_id = op1.person_id;
```
Its corresponding lines in runHeraclesAnalyses.sql are 498~509:
```
SELECT DISTINCT 
  YEAR(observation_period_start_date) AS obs_year,
  CAST(CAST(YEAR(observation_period_start_date) AS VARCHAR(4)) +  '01' + '01' AS DATE) AS obs_year_start,	
  CAST(CAST(YEAR(observation_period_start_date) AS VARCHAR(4)) +  '12' + '31' AS DATE) AS obs_year_end
INTO
  #temp_dates_1
from @CDM_schema.PERSON p1
inner join (select subject_id, cohort_definition_id as cohort_definition_id from @results_schema.COHORT where cohort_definition_id in (@cohort_definition_id)) c1
	on p1.person_id = c1.subject_id
inner join
  @CDM_schema.observation_period op1
  on p1.person_id = op1.person_id
;
```
Changing "AS DATE" to "as varchar2(30)" works. And simply removing the "cast" works too. I am not sure what the purpose is by casing to date in the temp table. 
Can anybody advise?

**Comment by chen-regen** [comment]
@anthonysena  @fdefalco Hi Frank and Anthony, I don't really know who to report to for this problem. So I am just pinging you guys here...

**Comment by anthonysena** [comment]
Thanks @chen-regen - we've got a few more fixes we're working on to the heraclesOptimization branch and I'm hoping I can take a look at this issue at the same time. We'll merge that work into the rc_2.3 branch so we can re-test. Thanks!
