### ISSUE TITLE
Error in Installion WebApI

### ISSUE THREAD

**Issue by jingsongs** [OHDSI/WebAPI#372]
Hello，I have a error  in installing the webapi, but I installed it with the standard steps. Could you give me some suggestions？
This is the error:
     29-Mar-2018 10:07:37.261 严重 [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/WebAPI]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shiroFilter' defined in class path resource [org/ohdsi/webapi/ShiroConfiguration.class]: Unsatisfied dependency expressed through method 'shiroFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/ohdsi/webapi/FlywayConfig.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration V1.0.1.1.1__penelope_data.sql failed
----------------------------------------------
SQL State  : 22008
Error Code : 0
Message    : 错误: 日期/时间值超出范围: "7/26/11"
  建议：也许你需要不同的 "datesytle" 设置.
  位置：240
Location   : db/migration/postgresql/V1.0.1.1.1__penelope_data.sql (D:\Program Files\apache-tomcat-8.5.29\webapps\WebAPI\WEB-INF\classes\db\migration\postgresql\V1.0.1.1.1__penelope_data.sql)
Line       : 96
Statement  : INSERT INTO drug_labels(drug_label_id, search_name, ingredient_concept_id, ingredient_concept_name, setid, date, cohort_id, image_url) VALUES(1, 'A+D DIAPER RASH (Topical)', '916662', 'dimethicone', '297e62e4-5282-4733-b3f7-f63a16e8ddee', '7/26/11', NULL, NULL)

	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:467)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:235)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:702)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:527)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5204)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more

**Comment by chrisknoll** [comment]
What happens when you try to insert that record manually?  you should get a more detailed error.  Note: after doing this test, you should delete the record (if it inserts) because you do not want a conflict with the migration script.

**Comment by jingsongs** [comment]
This is the detailed error,but I don‘t know where the error is.
Thank you very  much.    @chrisknoll 

2018-03-29 11:34:07.821 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Current version of schema "webapi": << Empty Schema >>
2018-03-29 11:34:07.821 WARN localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - outOfOrder mode is active. Migration of schema "webapi" may not be reproducible.
2018-03-29 11:34:07.824 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.1
2018-03-29 11:34:08.020 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.2
2018-03-29 11:34:08.061 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.3
2018-03-29 11:34:08.134 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.3.1
2018-03-29 11:34:08.176 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.3.2
2018-03-29 11:34:08.197 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.4
2018-03-29 11:34:08.403 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.4.1
2018-03-29 11:34:08.461 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.4.2
2018-03-29 11:34:08.501 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.4.3
2018-03-29 11:34:08.647 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.5
2018-03-29 11:34:08.739 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.5.1
2018-03-29 11:34:08.766 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.6.1
2018-03-29 11:34:08.781 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 表 "drug_hoi_evidence" 不存在
2018-03-29 11:34:08.782 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 序列 "drug_hoi_evidence_sequence" 不存在
2018-03-29 11:34:08.821 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 表 "evidence_sources" 不存在
2018-03-29 11:34:08.826 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 序列 "evidence_sources_sequence" 不存在
2018-03-29 11:34:08.850 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 表 "drug_hoi_relationship" 不存在
2018-03-29 11:34:08.868 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 表 "laertes_summary" 不存在
2018-03-29 11:34:08.870 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 序列 "laertes_summary_sequence" 不存在
2018-03-29 11:34:08.957 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.6.2
2018-03-29 11:34:08.981 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.6.3
2018-03-29 11:34:08.999 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.6.4
2018-03-29 11:34:09.022 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.6.5
2018-03-29 11:34:09.074 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.7.0
2018-03-29 11:34:09.116 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.7.1
2018-03-29 11:34:09.153 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.7.2
2018-03-29 11:34:09.187 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.8
2018-03-29 11:34:09.242 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.9
2018-03-29 11:34:09.355 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.0.9.1
2018-03-29 11:34:09.399 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.1.0
2018-03-29 11:34:09.401 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 表 "concept_set" 不存在
2018-03-29 11:34:09.403 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 序列 "concept_set_sequence" 不存在
2018-03-29 11:34:09.411 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 表 "concept_set_item" 不存在
2018-03-29 11:34:09.414 INFO localhost-startStop-1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: 序列 "concept_set_item_sequence" 不存在
2018-03-29 11:34:09.435 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.1.1
2018-03-29 11:34:09.516 INFO localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "webapi" to version 1.0.1.1.1
2018-03-29 11:34:10.045 ERROR localhost-startStop-1 org.flywaydb.core.internal.command.DbMigrate -  - Migration of schema "webapi" to version 1.0.1.1.1 failed! Changes successfully rolled back.
2018-03-29 11:34:10.051 WARN localhost-startStop-1 org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext -  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shiroFilter' defined in class path resource [org/ohdsi/webapi/ShiroConfiguration.class]: Unsatisfied dependency expressed through method 'shiroFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/ohdsi/webapi/FlywayConfig.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException:
Migration V1.0.1.1.1__penelope_data.sql failed
----------------------------------------------
SQL State  : 22008
Error Code : 0
Message    : 错误: 日期/时间值超出范围: "7/26/11"
  建议：也许你需要不同的 "datesytle" 设置.
  位置：240
Location   : db/migration/postgresql/V1.0.1.1.1__penelope_data.sql (D:\Program Files\apache-tomcat-8.5.29\webapps\WebAPI\WEB-INF\classes\db\migration\postgresql\V1.0.1.1.1__penelope_data.sql)
Line       : 96
Statement  : INSERT INTO drug_labels(drug_label_id, search_name, ingredient_concept_id, ingredient_concept_name, setid, date, cohort_id, image_url) VALUES(1, 'A+D DIAPER RASH (Topical)', '916662', 'dimethicone', '297e62e4-5282-4733-b3f7-f63a16e8ddee', '7/26/11', NULL, NULL)

2018-03-29 11:34:10.061 ERROR localhost-startStop-1 org.springframework.beans.factory.support.DefaultListableBeanFactory -  - Destroy method on bean with name 'dataSourceInitializer' threw an exception
java.lang.IllegalStateException: ApplicationEventMulticaster not initialized - call 'refresh' before multicasting events via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@61237056: startup date [Thu Mar 29 11:33:55 CST 2018]; root of context hierarchy
        at org.springframework.context.support.AbstractApplicationContext.getApplicationEventMulticaster(AbstractApplicationContext.java:404)
        at org.springframework.context.support.ApplicationListenerDetector.postProcessBeforeDestruction(ApplicationListenerDetector.java:97)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:555)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:151)
        at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:131)
        at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:86)
        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5204)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:986)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1857)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by chiyuan1126** [comment]
Just to let you know if you just want to install a local one and use it you can use the docker one https://github.com/OHDSI/Broadsea . That's easier.  If you would like to develop and contribute codes then you need to figure out those errors.

**Comment by chrisknoll** [comment]
The error is this insert statement fails:

```
INSERT INTO drug_labels(drug_label_id, search_name, ingredient_concept_id, ingredient_concept_name, setid, date, cohort_id, image_url) VALUES(1, 'A+D DIAPER RASH (Topical)', '916662', 'dimethicone', '297e62e4-5282-4733-b3f7-f63a16e8ddee', '7/26/11', NULL, NULL)
```

But the error in the log doesn't give the reason.  Please execute this statement on your SQL server directly to find out what the error is.  It might be a date format issue with '7/26/11' that does not look like a valid date format.

**Comment by anthonysena** [comment]
@chrisknoll - yes, that migration script is lacking the schema qualifier for PostgreSQL & Oracle so that is part of the issue. I can patch those scripts up to include that information.

@jingsongs - can you confirm your datestyle settings in PostgreSQL by running the following command:

`show datestyle;`

When I run this on my local PostgreSQL instance, I have the following:

> ISO, MDY

It could be that you have a different datestyle set and it should be adjusted to match the settings I have above using this information: https://www.postgresql.org/docs/7.2/static/sql-set.html. But please follow Chris' guidance and attempt to run that SQL statement directly and see what the error is. Based on the stack trace above, I agree with him that PostgreSQL is interpreting the format of '7/26/11' incorrectly.

**Comment by jingsongs** [comment]
I have solved this problem.It is the date format error that causes the issue.When I altered the datestyle
 in the postgresql.conf,the program could run  normally.Thanks for your help.  @anthonysena @chrisknoll @chiyuan1126

**Comment by limadm** [comment]
Hello,
My datestyle defaults to `'ISO, DMY'`, so I changed this option in postgresql.conf for now.
But don't you think that ISO dates by default are more straightforward for everyone?

**Comment by don-torok** [comment]
we fixed the problem in Postgres by doing an explicit to_date() case.  Wouldn't this be most likely to work regardless of the datestyle?

**Comment by pavgra** [comment]
I am in support of @don-torok 's proposal

**Comment by chrisknoll** [comment]
All statements with tables should have schema specified, including insert statements.
