### ISSUE TITLE
postgresql Permission denied for relation source 

### ISSUE THREAD

**Issue by vkramd** [OHDSI/WebAPI#540]
Hi,

I have deployed the WebAPI on tomcat server with the WebAPI cloned on 8th Aug. The two roles created are ohdsi_admin_user and the ohdsi_app_user as per the documentation. However the startup logs for the WebAPI shows error and the deployment is not completed. 

I found SQLState: 42501 in the error log. When i googled this i found that this pertains to not having correct permissions for various queries to be executed on the schema. Is the priviledges mentioned in documentation enough to run the queries or we need to give some more , as i am unable to run the select query with the user ohdsi_app_user. 

Attaching my error log for reference.

Hibernate: select source0_.SOURCE_ID as SOURCE_I1_35_, source0_.password as password2_35_, source0_.SOURCE_CONNECTION as SOURCE_C3_35_, source0_.SOURCE_DIALECT as SOURCE_D4_35_, source0_.SOURCE_KEY as SOURCE_K5_35_, source0_.SOURCE_NAME as SOURCE_N6_35_, source0_.username as username7_35_ from webapi.source source0_
2018-08-10 12:07:24.322 WARN http-bio-9099-exec-8 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - SQL Error: 0, SQLState: 42501
2018-08-10 12:07:24.323 ERROR http-bio-9099-exec-8 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - ERROR: permission denied for relation source
2018-08-10 12:07:24.328 DEBUG http-bio-9099-exec-8 org.springframework.orm.jpa.JpaTransactionManager -  - Participating transaction failed - marking existing transaction as rollback-only
2018-08-10 12:07:24.328 DEBUG http-bio-9099-exec-8 org.springframework.orm.jpa.JpaTransactionManager -  - Setting JPA transaction on EntityManager [org.hibernate.jpa.internal.EntityManagerImpl@17238b79] rollback-only
2018-08-10 12:07:24.334 DEBUG http-bio-9099-exec-8 org.springframework.orm.jpa.JpaTransactionManager -  - Initiating transaction rollback
2018-08-10 12:07:24.335 DEBUG http-bio-9099-exec-8 org.springframework.orm.jpa.JpaTransactionManager -  - Rolling back JPA transaction on EntityManager [org.hibernate.jpa.internal.EntityManagerImpl@17238b79]
2018-08-10 12:07:24.338 DEBUG http-bio-9099-exec-8 org.springframework.orm.jpa.JpaTransactionManager -  - Closing JPA EntityManager [org.hibernate.jpa.internal.EntityManagerImpl@17238b79] after transaction
2018-08-10 12:07:24.338 DEBUG http-bio-9099-exec-8 org.springframework.orm.jpa.EntityManagerFactoryUtils -  - Closing JPA EntityManager
2018-08-10 12:07:24.341 WARN http-bio-9099-exec-8 org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext -  - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'CDMResultsService': Invocation of init method failed; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
2018-08-10 12:07:24.341 INFO http-bio-9099-exec-8 org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor -  - Shutting down ExecutorService 'taskExecutor'
2018-08-10 12:07:24.355 INFO http-bio-9099-exec-8 org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer -  -

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-08-10 12:07:24.364 ERROR http-bio-9099-exec-8 org.springframework.boot.SpringApplication -  - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'CDMResultsService': Invocation of init method failed; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet

Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)

Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for relation source
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:305)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java

**Comment by chrisknoll** [comment]
Yes, that'sa  permission problem, and not a problem in WebAPI.  

The documentation has a section 'Prepare schema for WebAPI' which has this important note:

_*Note: this step is extremely important. If you do not assign default permissions when connected as the ohdsi_admin_user, the ohdsi_app_user account will not be granted the correct access privileges when the WebAPI creates the tables in the database!*_


It then describes how you create a new connection to PostgreSQL server but using the ohdsi_admin_user account to connect.  Did you follow that step?

The commands executed here are:

```
CREATE SCHEMA webapi
       AUTHORIZATION ohdsi_admin;
COMMENT ON SCHEMA webapi
  IS 'Schema containing tables to support WebAPI functionality';
GRANT USAGE ON SCHEMA webapi TO public;
GRANT ALL ON SCHEMA webapi TO GROUP ohdsi_admin;
GRANT USAGE ON SCHEMA webapi TO GROUP ohdsi_app;
```
That should set all new tables that are created in the schema to default to grant 'ALL' to ohdsi_admin and 'USAGE' to ohdsi_app.

You might need to alter your schema to set these default GRANTS for future tables, but then individually assign permissions to all the tables that were already created.  You may find it easier to start over.

**Comment by vkramd** [comment]
That was indeed a permission problem. I gave permission for the ohdsi_admin and ohdsi_app group users and was able to move forward.
