### ISSUE TITLE
cohort (treatment) pathways execution fails on Redshift

### ISSUE THREAD

**Issue by leeevans** [OHDSI/WebAPI#841]
Atlas/WebAPI cohort (treatment) pathways generation fails on Redshift with this error:

`java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [CREATE TABLE #split_overlapping_events DISTKEY(ELSE) AS SELECT CASE WHEN ordinal < 3 THEN first.id ELSE second.id END as id, CASE WHEN ordinal < 3 THEN first.event_cohort_index ELSE second.event_cohort_index END event_cohort_index, CASE WHEN ordinal < 3 THEN first. subject_id ELSE second.subject_id END subject_id, CASE ordinal WHEN 1 THEN first.cohort_start_date WHEN 2 THEN second.cohort_start_date WHEN 3 THEN second.cohort_start_date WHEN 4 THEN first.cohort_end_date END as cohort_start_date, CASE ordinal WHEN 1 THEN second.cohort_start_date WHEN 2 THEN first.cohort_end_date WHEN 3 THEN first.cohort_end_date WHEN 4 THEN second.cohort_end_date END as cohort_end_date FROM #collapsed_dates_events first JOIN #collapsed_dates_events second ON first.subject_id = second.subject_id AND first.cohort_start_date < second.cohort_start_date AND first.cohort_end_date < second.cohort_end_date AND first.cohort_end_date > second.cohort_start_date CROSS JOIN (SELECT 1 ordinal UNION SELECT 2 UNION SELECT 3 UNION SELECT 4) multiplier]; nested exception is java.sql.SQLException: [Amazon](500310) Invalid operation: syntax error at or near "ELSE" Position: 49; at org.ohdsi.webapi.common.generation.AnalysisTasklet.waitForFuture(AnalysisTasklet.java:62) at org.ohdsi.webapi.pathway.GeneratePathwayAnalysisTasklet.doTask(GeneratePathwayAnalysisTasklet.java:74) at `

The sqlrendered translation of the below SQL file from OHDISQL to Redshift SQL is producing the invalid DISTKEY(ELSE) clause in the target SQL. The DISTKEY translation seems to be confused by the 'SELECT CASE WHEN ELSE clause'.

https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/pathway/runPathwayAnalysis.sql

A workaround fix is to wrap the problem select case statement in an outer select.

i.e. 

```
IF OBJECT_ID('tempdb..#split_overlapping_events', 'U') IS NOT NULL
DROP TABLE #split_overlapping_events;

select *
from (
SELECT
        CASE WHEN ordinal < 3 THEN first.id ELSE second.id END as id,
        CASE WHEN ordinal < 3 THEN first.event_cohort_index ELSE second.event_cohort_index END event_cohort_index,
        CASE WHEN ordinal < 3 THEN first.subject_id ELSE second.subject_id END subject_id,

        CASE ordinal
                WHEN 1 THEN
                first.cohort_start_date
                WHEN 2 THEN
                second.cohort_start_date
                WHEN 3 THEN
                second.cohort_start_date
                WHEN 4 THEN
                first.cohort_end_date
                END as cohort_start_date,

        CASE ordinal
                WHEN 1 THEN
                second.cohort_start_date
                WHEN 2 THEN
                first.cohort_end_date
                WHEN 3 THEN
                first.cohort_end_date
                WHEN 4 THEN
                second.cohort_end_date
                END as cohort_end_date
FROM #collapsed_dates_events first
JOIN #collapsed_dates_events second ON first.subject_id = second.subject_id
    AND first.cohort_start_date < second.cohort_start_date
    AND first.cohort_end_date < second.cohort_end_date
    AND first.cohort_end_date > second.cohort_start_date
CROSS JOIN (SELECT 1 ordinal UNION SELECT 2 UNION SELECT 3 UNION SELECT 4) multiplier
)
INTO #split_overlapping_events
;

```

**Comment by pavgra** [comment]
Related to too specific rule in SqlRender
https://github.com/OHDSI/SqlRender/issues/160

**Comment by chrisknoll** [comment]
@pavgra , are you saying that @leeevans  work around (by including those case statements in a subquery) will not work?

**Comment by pavgra** [comment]
@chrisknoll , try to convert Lee's statement to PostgreSQL dialect with current SqlRender. You'll see that it renders "CREATE TABLE" instead of "CREATE TEMP TABLE". So it won't w/o changes for SqlRender. But if we would have time to change it (which I assume we don't have), the much simpler solution would be to wrap `subject_id` into double-quotes and that's it (but this requires additional translation of double-quotes to backticks)

**Comment by chrisknoll** [comment]
> You'll see that it renders "CREATE TABLE" instead of "CREATE TEMP TABLE". So it won't w/o changes for SqlRender

That's a pretty serious bug in SqlRender, since we use ```select ... INTO #tempTable``` in many places (especially in the runHeraclesAnalysis example: https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L84):

```
select subject_id, cohort_definition_id, cohort_start_date, cohort_end_date 
into #HERACLES_cohort
from @results_schema.cohort
where cohort_definition_id in (@cohort_definition_id)
```

So, you're saying, on PostgreSQL dialect, this does not create a temp table?

**Comment by pavgra** [comment]
My bad: I copied the SQL by @leeevans and pasted it into SqlRender w/o paying attention to the fact that the SQL is incorrect - it has SELECT-FROM-INTO instead of SELECT-INTO-FROM. With proper order it works, I've updated the PR
